--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

-- Started on 2025-09-22 20:29:08

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 6 (class 2615 OID 57972)
-- Name: game_1; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA game_1;


ALTER SCHEMA game_1 OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 224 (class 1259 OID 57989)
-- Name: accessToUnits; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1."accessToUnits" (
    id integer NOT NULL,
    "fk_Nation" integer NOT NULL,
    "fk_UnitTypes" integer NOT NULL
);


ALTER TABLE game_1."accessToUnits" OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 57992)
-- Name: accessToUnits_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1."accessToUnits" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1."accessToUnits_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 57993)
-- Name: accessestonations; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1.accessestonations (
    id integer NOT NULL,
    fk_nations integer NOT NULL,
    fk_users integer NOT NULL,
    dateacquired timestamp with time zone NOT NULL,
    isactive boolean NOT NULL
);


ALTER TABLE game_1.accessestonations OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 57996)
-- Name: accessestonations_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1.accessestonations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.accessestonations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 57997)
-- Name: actions; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1.actions (
    id integer NOT NULL,
    "fk_Nations" integer NOT NULL,
    name text,
    description text NOT NULL,
    result text,
    "isSettled" boolean NOT NULL
);


ALTER TABLE game_1.actions OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 58002)
-- Name: actions_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1.actions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.actions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 58003)
-- Name: armies; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1.armies (
    id integer NOT NULL,
    name text NOT NULL,
    "fk_Nations" integer NOT NULL,
    "fk_Locations" integer NOT NULL,
    is_naval boolean NOT NULL
);


ALTER TABLE game_1.armies OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 58008)
-- Name: armies_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1.armies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.armies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 58009)
-- Name: cultures; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1.cultures (
    id integer NOT NULL,
    name text NOT NULL
);


ALTER TABLE game_1.cultures OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 58014)
-- Name: cultures_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1.cultures ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.cultures_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 58015)
-- Name: events; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1.events (
    id integer NOT NULL,
    name text NOT NULL,
    description text,
    picture text
);


ALTER TABLE game_1.events OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 58020)
-- Name: events_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1.events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 58021)
-- Name: factions; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1.factions (
    id integer NOT NULL,
    name text NOT NULL,
    "fk_Nations" integer NOT NULL,
    power integer NOT NULL,
    agenda text NOT NULL,
    contentment integer NOT NULL,
    color text NOT NULL
);


ALTER TABLE game_1.factions OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 58026)
-- Name: factions_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1.factions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.factions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 58027)
-- Name: locations; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1.locations (
    id integer NOT NULL,
    name text NOT NULL,
    size integer NOT NULL,
    fortifications integer NOT NULL,
    fk_nations integer NOT NULL
);


ALTER TABLE game_1.locations OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 58032)
-- Name: locationsResources; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1."locationsResources" (
    id integer NOT NULL,
    "fk_Locations" integer NOT NULL,
    "fk_Resources" integer NOT NULL,
    amount double precision NOT NULL
);


ALTER TABLE game_1."locationsResources" OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 58035)
-- Name: locationsResources_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1."locationsResources" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1."locationsResources_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 241 (class 1259 OID 58036)
-- Name: locations_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1.locations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.locations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 242 (class 1259 OID 58037)
-- Name: maintenanceCosts; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1."maintenanceCosts" (
    id integer NOT NULL,
    "fk_UnitTypes" integer NOT NULL,
    "fk_Resources" integer NOT NULL,
    amount double precision NOT NULL
);


ALTER TABLE game_1."maintenanceCosts" OWNER TO postgres;

--
-- TOC entry 243 (class 1259 OID 58040)
-- Name: maintenanceCosts_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1."maintenanceCosts" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1."maintenanceCosts_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 244 (class 1259 OID 58041)
-- Name: map; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1.map (
    id integer NOT NULL,
    name text NOT NULL,
    "mapLocation" text NOT NULL,
    "mapIconLocation" text NOT NULL
);


ALTER TABLE game_1.map OWNER TO postgres;

--
-- TOC entry 245 (class 1259 OID 58046)
-- Name: mapAccess; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1."mapAccess" (
    "fk_Users" integer NOT NULL,
    "fk_Maps" integer NOT NULL
);


ALTER TABLE game_1."mapAccess" OWNER TO postgres;

--
-- TOC entry 246 (class 1259 OID 58049)
-- Name: map_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1.map ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.map_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 280 (class 1259 OID 58416)
-- Name: modifiers; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1.modifiers (
    id integer NOT NULL,
    event_id integer NOT NULL,
    modifier_type character varying(50) NOT NULL,
    effects jsonb NOT NULL
);


ALTER TABLE game_1.modifiers OWNER TO postgres;

--
-- TOC entry 279 (class 1259 OID 58415)
-- Name: modifiers_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

CREATE SEQUENCE game_1.modifiers_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE game_1.modifiers_id_seq OWNER TO postgres;

--
-- TOC entry 5126 (class 0 OID 0)
-- Dependencies: 279
-- Name: modifiers_id_seq; Type: SEQUENCE OWNED BY; Schema: game_1; Owner: postgres
--

ALTER SEQUENCE game_1.modifiers_id_seq OWNED BY game_1.modifiers.id;


--
-- TOC entry 247 (class 1259 OID 58050)
-- Name: nations; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1.nations (
    id integer NOT NULL,
    name text NOT NULL,
    fk_religions integer NOT NULL,
    fk_cultures integer NOT NULL,
    flag text,
    color text
);


ALTER TABLE game_1.nations OWNER TO postgres;

--
-- TOC entry 248 (class 1259 OID 58055)
-- Name: nations_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1.nations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.nations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 249 (class 1259 OID 58056)
-- Name: offeredresources; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1.offeredresources (
    id integer NOT NULL,
    fk_resource integer NOT NULL,
    fk_tradeagreement integer NOT NULL,
    quantity integer NOT NULL
);


ALTER TABLE game_1.offeredresources OWNER TO postgres;

--
-- TOC entry 250 (class 1259 OID 58059)
-- Name: offeredresources_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1.offeredresources ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.offeredresources_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 251 (class 1259 OID 58060)
-- Name: players; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1.players (
    id integer NOT NULL,
    "fk_User" integer NOT NULL,
    "playerType" integer NOT NULL
);


ALTER TABLE game_1.players OWNER TO postgres;

--
-- TOC entry 252 (class 1259 OID 58063)
-- Name: players_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1.players ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.players_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 282 (class 1259 OID 58436)
-- Name: populationproductionshares; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1.populationproductionshares (
    id integer NOT NULL,
    fk_population integer NOT NULL,
    fk_resources integer NOT NULL,
    coefficient double precision NOT NULL
);


ALTER TABLE game_1.populationproductionshares OWNER TO postgres;

--
-- TOC entry 281 (class 1259 OID 58435)
-- Name: populationproductionshares_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1.populationproductionshares ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME game_1.populationproductionshares_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 253 (class 1259 OID 58064)
-- Name: populations; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1.populations (
    id integer NOT NULL,
    fk_religions integer NOT NULL,
    fk_cultures integer NOT NULL,
    fk_socialgroups integer NOT NULL,
    fk_locations integer NOT NULL,
    happiness real NOT NULL,
    volunteers integer
);


ALTER TABLE game_1.populations OWNER TO postgres;

--
-- TOC entry 254 (class 1259 OID 58067)
-- Name: populations_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1.populations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.populations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 284 (class 1259 OID 58452)
-- Name: populationusedresource; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1.populationusedresource (
    id integer NOT NULL,
    fk_population integer NOT NULL,
    fk_resources integer NOT NULL,
    amount double precision NOT NULL
);


ALTER TABLE game_1.populationusedresource OWNER TO postgres;

--
-- TOC entry 283 (class 1259 OID 58451)
-- Name: populationusedresource_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1.populationusedresource ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME game_1.populationusedresource_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 255 (class 1259 OID 58068)
-- Name: productionCost; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1."productionCost" (
    id integer NOT NULL,
    "fk_UnitTypes" integer NOT NULL,
    "fk_Resources" integer NOT NULL,
    amount double precision NOT NULL
);


ALTER TABLE game_1."productionCost" OWNER TO postgres;

--
-- TOC entry 256 (class 1259 OID 58071)
-- Name: productionCost_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1."productionCost" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1."productionCost_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 257 (class 1259 OID 58072)
-- Name: productionShares; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1."productionShares" (
    id integer NOT NULL,
    "fk_SocialGroups" integer NOT NULL,
    "fk_Resources" integer NOT NULL,
    coefficient double precision NOT NULL
);


ALTER TABLE game_1."productionShares" OWNER TO postgres;

--
-- TOC entry 258 (class 1259 OID 58075)
-- Name: productionShares_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1."productionShares" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1."productionShares_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 259 (class 1259 OID 58076)
-- Name: relatedEvents; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1."relatedEvents" (
    id integer NOT NULL,
    "fk_Events" integer NOT NULL,
    "fk_Nations" integer NOT NULL
);


ALTER TABLE game_1."relatedEvents" OWNER TO postgres;

--
-- TOC entry 260 (class 1259 OID 58079)
-- Name: relatedEvents_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1."relatedEvents" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1."relatedEvents_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 261 (class 1259 OID 58080)
-- Name: religions; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1.religions (
    id integer NOT NULL,
    name text NOT NULL,
    icon text
);


ALTER TABLE game_1.religions OWNER TO postgres;

--
-- TOC entry 262 (class 1259 OID 58085)
-- Name: religions_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1.religions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.religions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 263 (class 1259 OID 58086)
-- Name: resources; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1.resources (
    id integer NOT NULL,
    name text NOT NULL,
    ismain boolean NOT NULL,
    icon text
);


ALTER TABLE game_1.resources OWNER TO postgres;

--
-- TOC entry 264 (class 1259 OID 58091)
-- Name: resources_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1.resources ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.resources_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 265 (class 1259 OID 58092)
-- Name: socialgroups; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1.socialgroups (
    id integer NOT NULL,
    name text NOT NULL,
    basehappiness real NOT NULL,
    volunteers integer NOT NULL,
    icon text
);


ALTER TABLE game_1.socialgroups OWNER TO postgres;

--
-- TOC entry 266 (class 1259 OID 58097)
-- Name: socialgroups_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1.socialgroups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.socialgroups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 267 (class 1259 OID 58098)
-- Name: tradeagreements; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1.tradeagreements (
    id integer NOT NULL,
    fk_nationoffering integer NOT NULL,
    fk_nationreceiving integer NOT NULL,
    status integer NOT NULL,
    duration integer NOT NULL,
    description text NOT NULL
);


ALTER TABLE game_1.tradeagreements OWNER TO postgres;

--
-- TOC entry 268 (class 1259 OID 58103)
-- Name: tradeagreements_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1.tradeagreements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.tradeagreements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 269 (class 1259 OID 58104)
-- Name: troops; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1.troops (
    id integer NOT NULL,
    "fk_UnitTypes" integer NOT NULL,
    "fk_Armies" integer NOT NULL,
    quantity integer NOT NULL
);


ALTER TABLE game_1.troops OWNER TO postgres;

--
-- TOC entry 270 (class 1259 OID 58107)
-- Name: troops_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1.troops ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.troops_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 271 (class 1259 OID 58108)
-- Name: unitOrders; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1."unitOrders" (
    id integer NOT NULL,
    "fk_UnitTypes" integer NOT NULL,
    "fk_Nations" integer NOT NULL,
    quantity integer NOT NULL
);


ALTER TABLE game_1."unitOrders" OWNER TO postgres;

--
-- TOC entry 272 (class 1259 OID 58111)
-- Name: unitOrders_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1."unitOrders" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1."unitOrders_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 273 (class 1259 OID 58112)
-- Name: unitTypes; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1."unitTypes" (
    id integer NOT NULL,
    name text NOT NULL,
    description text NOT NULL,
    melee integer NOT NULL,
    range integer NOT NULL,
    defense integer NOT NULL,
    speed integer NOT NULL,
    morale integer NOT NULL,
    "volunteersNeeded" integer NOT NULL,
    "isNaval" boolean NOT NULL
);


ALTER TABLE game_1."unitTypes" OWNER TO postgres;

--
-- TOC entry 274 (class 1259 OID 58117)
-- Name: unitTypes_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1."unitTypes" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1."unitTypes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 275 (class 1259 OID 58118)
-- Name: usedResources; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1."usedResources" (
    id integer NOT NULL,
    "fk_SocialGroups" integer NOT NULL,
    "fk_Resources" integer NOT NULL,
    amount double precision NOT NULL
);


ALTER TABLE game_1."usedResources" OWNER TO postgres;

--
-- TOC entry 276 (class 1259 OID 58121)
-- Name: usedResources_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1."usedResources" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1."usedResources_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 277 (class 1259 OID 58122)
-- Name: wantedresources; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1.wantedresources (
    id integer NOT NULL,
    fk_resource integer NOT NULL,
    fk_tradeagreement integer NOT NULL,
    amount double precision NOT NULL
);


ALTER TABLE game_1.wantedresources OWNER TO postgres;

--
-- TOC entry 278 (class 1259 OID 58125)
-- Name: wantedresources_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1.wantedresources ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.wantedresources_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4857 (class 2604 OID 58419)
-- Name: modifiers id; Type: DEFAULT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.modifiers ALTER COLUMN id SET DEFAULT nextval('game_1.modifiers_id_seq'::regclass);


--
-- TOC entry 4861 (class 2606 OID 58133)
-- Name: accessToUnits PK_accessToUnits; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1."accessToUnits"
    ADD CONSTRAINT "PK_accessToUnits" PRIMARY KEY (id);


--
-- TOC entry 4865 (class 2606 OID 58135)
-- Name: accessestonations PK_accessestonations; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.accessestonations
    ADD CONSTRAINT "PK_accessestonations" PRIMARY KEY (id);


--
-- TOC entry 4868 (class 2606 OID 58137)
-- Name: actions PK_actions; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.actions
    ADD CONSTRAINT "PK_actions" PRIMARY KEY (id);


--
-- TOC entry 4872 (class 2606 OID 58139)
-- Name: armies PK_armies; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.armies
    ADD CONSTRAINT "PK_armies" PRIMARY KEY (id);


--
-- TOC entry 4874 (class 2606 OID 58141)
-- Name: cultures PK_cultures; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.cultures
    ADD CONSTRAINT "PK_cultures" PRIMARY KEY (id);


--
-- TOC entry 4876 (class 2606 OID 58143)
-- Name: events PK_events; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.events
    ADD CONSTRAINT "PK_events" PRIMARY KEY (id);


--
-- TOC entry 4879 (class 2606 OID 58145)
-- Name: factions PK_factions; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.factions
    ADD CONSTRAINT "PK_factions" PRIMARY KEY (id);


--
-- TOC entry 4882 (class 2606 OID 58147)
-- Name: locations PK_locations; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.locations
    ADD CONSTRAINT "PK_locations" PRIMARY KEY (id);


--
-- TOC entry 4884 (class 2606 OID 58149)
-- Name: locationsResources PK_locationsResources; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1."locationsResources"
    ADD CONSTRAINT "PK_locationsResources" PRIMARY KEY (id);


--
-- TOC entry 4888 (class 2606 OID 58151)
-- Name: maintenanceCosts PK_maintenanceCosts; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1."maintenanceCosts"
    ADD CONSTRAINT "PK_maintenanceCosts" PRIMARY KEY (id);


--
-- TOC entry 4890 (class 2606 OID 58153)
-- Name: map PK_map; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.map
    ADD CONSTRAINT "PK_map" PRIMARY KEY (id);


--
-- TOC entry 4893 (class 2606 OID 58155)
-- Name: mapAccess PK_mapAccess; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1."mapAccess"
    ADD CONSTRAINT "PK_mapAccess" PRIMARY KEY ("fk_Users", "fk_Maps");


--
-- TOC entry 4895 (class 2606 OID 58157)
-- Name: nations PK_nations; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.nations
    ADD CONSTRAINT "PK_nations" PRIMARY KEY (id);


--
-- TOC entry 4899 (class 2606 OID 58159)
-- Name: offeredresources PK_offeredresources; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.offeredresources
    ADD CONSTRAINT "PK_offeredresources" PRIMARY KEY (id);


--
-- TOC entry 4901 (class 2606 OID 58161)
-- Name: players PK_players; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.players
    ADD CONSTRAINT "PK_players" PRIMARY KEY (id);


--
-- TOC entry 4907 (class 2606 OID 58163)
-- Name: populations PK_populations; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.populations
    ADD CONSTRAINT "PK_populations" PRIMARY KEY (id);


--
-- TOC entry 4911 (class 2606 OID 58165)
-- Name: productionCost PK_productionCost; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1."productionCost"
    ADD CONSTRAINT "PK_productionCost" PRIMARY KEY (id);


--
-- TOC entry 4913 (class 2606 OID 58167)
-- Name: productionShares PK_productionShares; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1."productionShares"
    ADD CONSTRAINT "PK_productionShares" PRIMARY KEY (id);


--
-- TOC entry 4917 (class 2606 OID 58169)
-- Name: relatedEvents PK_relatedEvents; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1."relatedEvents"
    ADD CONSTRAINT "PK_relatedEvents" PRIMARY KEY (id);


--
-- TOC entry 4919 (class 2606 OID 58171)
-- Name: religions PK_religions; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.religions
    ADD CONSTRAINT "PK_religions" PRIMARY KEY (id);


--
-- TOC entry 4921 (class 2606 OID 58173)
-- Name: resources PK_resources; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.resources
    ADD CONSTRAINT "PK_resources" PRIMARY KEY (id);


--
-- TOC entry 4923 (class 2606 OID 58175)
-- Name: socialgroups PK_socialgroups; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.socialgroups
    ADD CONSTRAINT "PK_socialgroups" PRIMARY KEY (id);


--
-- TOC entry 4927 (class 2606 OID 58177)
-- Name: tradeagreements PK_tradeagreements; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.tradeagreements
    ADD CONSTRAINT "PK_tradeagreements" PRIMARY KEY (id);


--
-- TOC entry 4931 (class 2606 OID 58179)
-- Name: troops PK_troops; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.troops
    ADD CONSTRAINT "PK_troops" PRIMARY KEY (id);


--
-- TOC entry 4935 (class 2606 OID 58181)
-- Name: unitOrders PK_unitOrders; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1."unitOrders"
    ADD CONSTRAINT "PK_unitOrders" PRIMARY KEY (id);


--
-- TOC entry 4937 (class 2606 OID 58183)
-- Name: unitTypes PK_unitTypes; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1."unitTypes"
    ADD CONSTRAINT "PK_unitTypes" PRIMARY KEY (id);


--
-- TOC entry 4939 (class 2606 OID 58185)
-- Name: usedResources PK_usedResources; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1."usedResources"
    ADD CONSTRAINT "PK_usedResources" PRIMARY KEY (id);


--
-- TOC entry 4943 (class 2606 OID 58187)
-- Name: wantedresources PK_wantedresources; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.wantedresources
    ADD CONSTRAINT "PK_wantedresources" PRIMARY KEY (id);


--
-- TOC entry 4945 (class 2606 OID 58423)
-- Name: modifiers modifiers_pkey; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.modifiers
    ADD CONSTRAINT modifiers_pkey PRIMARY KEY (id);


--
-- TOC entry 4947 (class 2606 OID 58440)
-- Name: populationproductionshares populationproductionshares_pkey; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.populationproductionshares
    ADD CONSTRAINT populationproductionshares_pkey PRIMARY KEY (id);


--
-- TOC entry 4949 (class 2606 OID 58456)
-- Name: populationusedresource populationusedresource_pkey; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.populationusedresource
    ADD CONSTRAINT populationusedresource_pkey PRIMARY KEY (id);


--
-- TOC entry 4858 (class 1259 OID 58193)
-- Name: IX_accessToUnits_fk_Nations; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_accessToUnits_fk_Nations" ON game_1."accessToUnits" USING btree ("fk_Nation");


--
-- TOC entry 4859 (class 1259 OID 58194)
-- Name: IX_accessToUnits_fk_UnitTypes; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_accessToUnits_fk_UnitTypes" ON game_1."accessToUnits" USING btree ("fk_UnitTypes");


--
-- TOC entry 4862 (class 1259 OID 58195)
-- Name: IX_accessestonations_fk_nations; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_accessestonations_fk_nations" ON game_1.accessestonations USING btree (fk_nations);


--
-- TOC entry 4863 (class 1259 OID 58196)
-- Name: IX_accessestonations_fk_users; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_accessestonations_fk_users" ON game_1.accessestonations USING btree (fk_users);


--
-- TOC entry 4866 (class 1259 OID 58197)
-- Name: IX_actions_fk_Nations; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_actions_fk_Nations" ON game_1.actions USING btree ("fk_Nations");


--
-- TOC entry 4869 (class 1259 OID 58198)
-- Name: IX_armies_fk_Locations; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_armies_fk_Locations" ON game_1.armies USING btree ("fk_Locations");


--
-- TOC entry 4870 (class 1259 OID 58199)
-- Name: IX_armies_fk_Nations; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_armies_fk_Nations" ON game_1.armies USING btree ("fk_Nations");


--
-- TOC entry 4877 (class 1259 OID 58200)
-- Name: IX_factions_fk_Nations; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_factions_fk_Nations" ON game_1.factions USING btree ("fk_Nations");


--
-- TOC entry 4880 (class 1259 OID 58201)
-- Name: IX_locations_fk_nations; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_locations_fk_nations" ON game_1.locations USING btree (fk_nations);


--
-- TOC entry 4885 (class 1259 OID 58202)
-- Name: IX_maintenanceCosts_fk_Resources; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_maintenanceCosts_fk_Resources" ON game_1."maintenanceCosts" USING btree ("fk_Resources");


--
-- TOC entry 4886 (class 1259 OID 58203)
-- Name: IX_maintenanceCosts_fk_UnitTypes; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_maintenanceCosts_fk_UnitTypes" ON game_1."maintenanceCosts" USING btree ("fk_UnitTypes");


--
-- TOC entry 4891 (class 1259 OID 58204)
-- Name: IX_mapAccess_fk_Maps; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_mapAccess_fk_Maps" ON game_1."mapAccess" USING btree ("fk_Maps");


--
-- TOC entry 4896 (class 1259 OID 58205)
-- Name: IX_offeredresources_fk_resource; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_offeredresources_fk_resource" ON game_1.offeredresources USING btree (fk_resource);


--
-- TOC entry 4897 (class 1259 OID 58206)
-- Name: IX_offeredresources_fk_tradeagreement; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_offeredresources_fk_tradeagreement" ON game_1.offeredresources USING btree (fk_tradeagreement);


--
-- TOC entry 4902 (class 1259 OID 58207)
-- Name: IX_populations_fk_cultures; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_populations_fk_cultures" ON game_1.populations USING btree (fk_cultures);


--
-- TOC entry 4903 (class 1259 OID 58208)
-- Name: IX_populations_fk_locations; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_populations_fk_locations" ON game_1.populations USING btree (fk_locations);


--
-- TOC entry 4904 (class 1259 OID 58209)
-- Name: IX_populations_fk_religions; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_populations_fk_religions" ON game_1.populations USING btree (fk_religions);


--
-- TOC entry 4905 (class 1259 OID 58210)
-- Name: IX_populations_fk_socialgroups; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_populations_fk_socialgroups" ON game_1.populations USING btree (fk_socialgroups);


--
-- TOC entry 4908 (class 1259 OID 58211)
-- Name: IX_productionCost_fk_Resources; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_productionCost_fk_Resources" ON game_1."productionCost" USING btree ("fk_Resources");


--
-- TOC entry 4909 (class 1259 OID 58212)
-- Name: IX_productionCost_fk_UnitTypes; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_productionCost_fk_UnitTypes" ON game_1."productionCost" USING btree ("fk_UnitTypes");


--
-- TOC entry 4914 (class 1259 OID 58213)
-- Name: IX_relatedEvents_fk_Events; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_relatedEvents_fk_Events" ON game_1."relatedEvents" USING btree ("fk_Events");


--
-- TOC entry 4915 (class 1259 OID 58214)
-- Name: IX_relatedEvents_fk_Nations; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_relatedEvents_fk_Nations" ON game_1."relatedEvents" USING btree ("fk_Nations");


--
-- TOC entry 4924 (class 1259 OID 58215)
-- Name: IX_tradeagreements_fk_nationoffering; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_tradeagreements_fk_nationoffering" ON game_1.tradeagreements USING btree (fk_nationoffering);


--
-- TOC entry 4925 (class 1259 OID 58216)
-- Name: IX_tradeagreements_fk_nationreceiving; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_tradeagreements_fk_nationreceiving" ON game_1.tradeagreements USING btree (fk_nationreceiving);


--
-- TOC entry 4928 (class 1259 OID 58217)
-- Name: IX_troops_fk_Armies; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_troops_fk_Armies" ON game_1.troops USING btree ("fk_Armies");


--
-- TOC entry 4929 (class 1259 OID 58218)
-- Name: IX_troops_fk_UnitTypes; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_troops_fk_UnitTypes" ON game_1.troops USING btree ("fk_UnitTypes");


--
-- TOC entry 4932 (class 1259 OID 58219)
-- Name: IX_unitOrders_fk_Nations; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_unitOrders_fk_Nations" ON game_1."unitOrders" USING btree ("fk_Nations");


--
-- TOC entry 4933 (class 1259 OID 58220)
-- Name: IX_unitOrders_fk_UnitTypes; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_unitOrders_fk_UnitTypes" ON game_1."unitOrders" USING btree ("fk_UnitTypes");


--
-- TOC entry 4940 (class 1259 OID 58221)
-- Name: IX_wantedresources_fk_resource; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_wantedresources_fk_resource" ON game_1.wantedresources USING btree (fk_resource);


--
-- TOC entry 4941 (class 1259 OID 58222)
-- Name: IX_wantedresources_fk_tradeagreement; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_wantedresources_fk_tradeagreement" ON game_1.wantedresources USING btree (fk_tradeagreement);


--
-- TOC entry 4950 (class 2606 OID 58263)
-- Name: armies FK_armies_locations_fk_Locations; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.armies
    ADD CONSTRAINT "FK_armies_locations_fk_Locations" FOREIGN KEY ("fk_Locations") REFERENCES game_1.locations(id) ON DELETE CASCADE;


--
-- TOC entry 4951 (class 2606 OID 58278)
-- Name: locationsResources FK_locationsResources_locations_fk_Locations; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1."locationsResources"
    ADD CONSTRAINT "FK_locationsResources_locations_fk_Locations" FOREIGN KEY ("fk_Locations") REFERENCES game_1.locations(id) ON DELETE CASCADE;


--
-- TOC entry 4952 (class 2606 OID 58303)
-- Name: mapAccess FK_mapAccess_map_fk_Maps; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1."mapAccess"
    ADD CONSTRAINT "FK_mapAccess_map_fk_Maps" FOREIGN KEY ("fk_Maps") REFERENCES game_1.map(id) ON DELETE CASCADE;


--
-- TOC entry 4953 (class 2606 OID 58313)
-- Name: offeredresources FK_offeredresources_resources_fk_resource; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.offeredresources
    ADD CONSTRAINT "FK_offeredresources_resources_fk_resource" FOREIGN KEY (fk_resource) REFERENCES game_1.resources(id) ON DELETE CASCADE;


--
-- TOC entry 4954 (class 2606 OID 58318)
-- Name: offeredresources FK_offeredresources_tradeagreements_fk_tradeagreement; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.offeredresources
    ADD CONSTRAINT "FK_offeredresources_tradeagreements_fk_tradeagreement" FOREIGN KEY (fk_tradeagreement) REFERENCES game_1.tradeagreements(id) ON DELETE CASCADE;


--
-- TOC entry 4955 (class 2606 OID 58323)
-- Name: populations FK_populations_cultures_fk_cultures; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.populations
    ADD CONSTRAINT "FK_populations_cultures_fk_cultures" FOREIGN KEY (fk_cultures) REFERENCES game_1.cultures(id) ON DELETE CASCADE;


--
-- TOC entry 4956 (class 2606 OID 58328)
-- Name: populations FK_populations_locations_fk_locations; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.populations
    ADD CONSTRAINT "FK_populations_locations_fk_locations" FOREIGN KEY (fk_locations) REFERENCES game_1.locations(id) ON DELETE CASCADE;


--
-- TOC entry 4957 (class 2606 OID 58333)
-- Name: populations FK_populations_religions_fk_religions; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.populations
    ADD CONSTRAINT "FK_populations_religions_fk_religions" FOREIGN KEY (fk_religions) REFERENCES game_1.religions(id) ON DELETE CASCADE;


--
-- TOC entry 4958 (class 2606 OID 58338)
-- Name: populations FK_populations_socialgroups_fk_socialgroups; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.populations
    ADD CONSTRAINT "FK_populations_socialgroups_fk_socialgroups" FOREIGN KEY (fk_socialgroups) REFERENCES game_1.socialgroups(id) ON DELETE CASCADE;


--
-- TOC entry 4959 (class 2606 OID 58343)
-- Name: productionCost FK_productionCost_resources_fk_Resources; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1."productionCost"
    ADD CONSTRAINT "FK_productionCost_resources_fk_Resources" FOREIGN KEY ("fk_Resources") REFERENCES game_1.resources(id) ON DELETE CASCADE;


--
-- TOC entry 4960 (class 2606 OID 58348)
-- Name: productionCost FK_productionCost_unitTypes_fk_UnitTypes; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1."productionCost"
    ADD CONSTRAINT "FK_productionCost_unitTypes_fk_UnitTypes" FOREIGN KEY ("fk_UnitTypes") REFERENCES game_1."unitTypes"(id) ON DELETE CASCADE;


--
-- TOC entry 4961 (class 2606 OID 58353)
-- Name: relatedEvents FK_relatedEvents_events_fk_Events; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1."relatedEvents"
    ADD CONSTRAINT "FK_relatedEvents_events_fk_Events" FOREIGN KEY ("fk_Events") REFERENCES game_1.events(id) ON DELETE CASCADE;


--
-- TOC entry 4962 (class 2606 OID 58358)
-- Name: relatedEvents FK_relatedEvents_nations_fk_Nations; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1."relatedEvents"
    ADD CONSTRAINT "FK_relatedEvents_nations_fk_Nations" FOREIGN KEY ("fk_Nations") REFERENCES game_1.nations(id) ON DELETE CASCADE;


--
-- TOC entry 4963 (class 2606 OID 58363)
-- Name: tradeagreements FK_tradeagreements_nations_fk_nationoffering; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.tradeagreements
    ADD CONSTRAINT "FK_tradeagreements_nations_fk_nationoffering" FOREIGN KEY (fk_nationoffering) REFERENCES game_1.nations(id) ON DELETE CASCADE;


--
-- TOC entry 4964 (class 2606 OID 58368)
-- Name: tradeagreements FK_tradeagreements_nations_fk_nationreceiving; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.tradeagreements
    ADD CONSTRAINT "FK_tradeagreements_nations_fk_nationreceiving" FOREIGN KEY (fk_nationreceiving) REFERENCES game_1.nations(id) ON DELETE CASCADE;


--
-- TOC entry 4965 (class 2606 OID 58373)
-- Name: troops FK_troops_armies_fk_Armies; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.troops
    ADD CONSTRAINT "FK_troops_armies_fk_Armies" FOREIGN KEY ("fk_Armies") REFERENCES game_1.armies(id) ON DELETE CASCADE;


--
-- TOC entry 4966 (class 2606 OID 58378)
-- Name: troops FK_troops_unitTypes_fk_UnitTypes; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.troops
    ADD CONSTRAINT "FK_troops_unitTypes_fk_UnitTypes" FOREIGN KEY ("fk_UnitTypes") REFERENCES game_1."unitTypes"(id) ON DELETE CASCADE;


--
-- TOC entry 4967 (class 2606 OID 58383)
-- Name: unitOrders FK_unitOrders_nations_fk_Nations; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1."unitOrders"
    ADD CONSTRAINT "FK_unitOrders_nations_fk_Nations" FOREIGN KEY ("fk_Nations") REFERENCES game_1.nations(id) ON DELETE CASCADE;


--
-- TOC entry 4968 (class 2606 OID 58388)
-- Name: unitOrders FK_unitOrders_unitTypes_fk_UnitTypes; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1."unitOrders"
    ADD CONSTRAINT "FK_unitOrders_unitTypes_fk_UnitTypes" FOREIGN KEY ("fk_UnitTypes") REFERENCES game_1."unitTypes"(id) ON DELETE CASCADE;


--
-- TOC entry 4969 (class 2606 OID 58393)
-- Name: wantedresources FK_wantedresources_resources_fk_resource; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.wantedresources
    ADD CONSTRAINT "FK_wantedresources_resources_fk_resource" FOREIGN KEY (fk_resource) REFERENCES game_1.resources(id) ON DELETE CASCADE;


--
-- TOC entry 4970 (class 2606 OID 58398)
-- Name: wantedresources FK_wantedresources_tradeagreements_fk_tradeagreement; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.wantedresources
    ADD CONSTRAINT "FK_wantedresources_tradeagreements_fk_tradeagreement" FOREIGN KEY (fk_tradeagreement) REFERENCES game_1.tradeagreements(id) ON DELETE CASCADE;


--
-- TOC entry 4971 (class 2606 OID 58424)
-- Name: modifiers modifiers_event_id_fkey; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.modifiers
    ADD CONSTRAINT modifiers_event_id_fkey FOREIGN KEY (event_id) REFERENCES game_1.events(id) ON DELETE CASCADE;


--
-- TOC entry 4972 (class 2606 OID 58441)
-- Name: populationproductionshares populationproductionshares_fkpopulation_fkey; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.populationproductionshares
    ADD CONSTRAINT populationproductionshares_fkpopulation_fkey FOREIGN KEY (fk_population) REFERENCES game_1.populations(id) ON DELETE CASCADE;


--
-- TOC entry 4973 (class 2606 OID 58446)
-- Name: populationproductionshares populationproductionshares_fkresources_fkey; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.populationproductionshares
    ADD CONSTRAINT populationproductionshares_fkresources_fkey FOREIGN KEY (fk_resources) REFERENCES game_1.resources(id) ON DELETE CASCADE;


--
-- TOC entry 4974 (class 2606 OID 58457)
-- Name: populationusedresource populationusedresource_fkpopulation_fkey; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.populationusedresource
    ADD CONSTRAINT populationusedresource_fkpopulation_fkey FOREIGN KEY (fk_population) REFERENCES game_1.populations(id) ON DELETE CASCADE;


--
-- TOC entry 4975 (class 2606 OID 58462)
-- Name: populationusedresource populationusedresource_fkresources_fkey; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.populationusedresource
    ADD CONSTRAINT populationusedresource_fkresources_fkey FOREIGN KEY (fk_resources) REFERENCES game_1.resources(id) ON DELETE CASCADE;


-- Completed on 2025-09-22 20:29:08

--
-- PostgreSQL database dump complete
--

