--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: game_1; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA game_1;


--
-- Name: add_nation_to_all_resources(); Type: FUNCTION; Schema: game_1; Owner: -
--

CREATE FUNCTION game_1.add_nation_to_all_resources() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
    nationId INT := NEW.id;
BEGIN
    INSERT INTO game_1."ownedResources" (fk_nation, fk_resource, amount)
    SELECT nationId, r.id, 0
    FROM game_1.resources r;

    RETURN NEW;
END;
$$;


--
-- Name: add_population_relations(); Type: FUNCTION; Schema: game_1; Owner: -
--

CREATE FUNCTION game_1.add_population_relations() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
    socialGroupId INT := NEW.fk_socialgroups;
    popId INT := NEW.id;
BEGIN
    -- Tworzenie rekordów w populationproductionshares
    INSERT INTO game_1.populationproductionshares (fk_population, fk_resources, coefficient)
    SELECT popId, ps."fk_Resources", ps.coefficient
    FROM game_1."productionShares" ps
    WHERE ps."fk_SocialGroups" = socialGroupId;

    -- Tworzenie rekordów w populationusedresource
    INSERT INTO game_1.populationusedresource (fk_population, fk_resources, amount)
    SELECT popId, ur."fk_Resources", ur.amount
    FROM game_1."usedResources" ur
    WHERE ur."fk_SocialGroups" = socialGroupId;

    RETURN NEW;
END;
$$;


--
-- Name: add_production_shares_to_populations(); Type: FUNCTION; Schema: game_1; Owner: -
--

CREATE FUNCTION game_1.add_production_shares_to_populations() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
    socialGroupId INT := NEW."fk_SocialGroups";
BEGIN
    INSERT INTO game_1.populationproductionshares (fk_population, fk_resources, coefficient)
    SELECT p.id, NEW."fk_Resources", NEW.coefficient
    FROM game_1.populations p
    WHERE p.fk_socialgroups = socialGroupId;

    RETURN NEW;
END;
$$;


--
-- Name: add_resource_to_all_nations(); Type: FUNCTION; Schema: game_1; Owner: -
--

CREATE FUNCTION game_1.add_resource_to_all_nations() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
    resourceId INT := NEW.id;
BEGIN
    INSERT INTO game_1."ownedResources" (fk_nation, fk_resource, amount)
    SELECT n.id, resourceId, 0
    FROM game_1.nations n;

    RETURN NEW;
END;
$$;


--
-- Name: add_used_resources_to_populations(); Type: FUNCTION; Schema: game_1; Owner: -
--

CREATE FUNCTION game_1.add_used_resources_to_populations() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
    socialGroupId INT := NEW."fk_SocialGroups";
BEGIN
    INSERT INTO game_1.populationusedresource (fk_population, fk_resources, amount)
    SELECT p.id, NEW."fk_Resources", NEW.amount
    FROM game_1.populations p
    WHERE p.fk_socialgroups = socialGroupId;

    RETURN NEW;
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accessToUnits; Type: TABLE; Schema: game_1; Owner: -
--

CREATE TABLE game_1."accessToUnits" (
    id integer NOT NULL,
    "fk_Nation" integer NOT NULL,
    "fk_UnitTypes" integer NOT NULL
);


--
-- Name: accessToUnits_id_seq; Type: SEQUENCE; Schema: game_1; Owner: -
--

ALTER TABLE game_1."accessToUnits" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1."accessToUnits_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accessestonations; Type: TABLE; Schema: game_1; Owner: -
--

CREATE TABLE game_1.accessestonations (
    id integer NOT NULL,
    fk_nations integer NOT NULL,
    fk_users integer NOT NULL,
    dateacquired timestamp with time zone NOT NULL,
    isactive boolean NOT NULL
);


--
-- Name: accessestonations_id_seq; Type: SEQUENCE; Schema: game_1; Owner: -
--

ALTER TABLE game_1.accessestonations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.accessestonations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: actions; Type: TABLE; Schema: game_1; Owner: -
--

CREATE TABLE game_1.actions (
    id integer NOT NULL,
    "fk_Nations" integer NOT NULL,
    name text,
    description text NOT NULL,
    result text,
    "isSettled" boolean NOT NULL
);


--
-- Name: actions_id_seq; Type: SEQUENCE; Schema: game_1; Owner: -
--

ALTER TABLE game_1.actions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.actions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: armies; Type: TABLE; Schema: game_1; Owner: -
--

CREATE TABLE game_1.armies (
    id integer NOT NULL,
    name text NOT NULL,
    "fk_Nations" integer NOT NULL,
    fk_localisations integer NOT NULL,
    is_naval boolean NOT NULL
);


--
-- Name: armies_id_seq; Type: SEQUENCE; Schema: game_1; Owner: -
--

ALTER TABLE game_1.armies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.armies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cultures; Type: TABLE; Schema: game_1; Owner: -
--

CREATE TABLE game_1.cultures (
    id integer NOT NULL,
    name text NOT NULL
);


--
-- Name: cultures_id_seq; Type: SEQUENCE; Schema: game_1; Owner: -
--

ALTER TABLE game_1.cultures ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.cultures_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: events; Type: TABLE; Schema: game_1; Owner: -
--

CREATE TABLE game_1.events (
    id integer NOT NULL,
    name text NOT NULL,
    description text,
    picture text
);


--
-- Name: events_id_seq; Type: SEQUENCE; Schema: game_1; Owner: -
--

ALTER TABLE game_1.events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: factions; Type: TABLE; Schema: game_1; Owner: -
--

CREATE TABLE game_1.factions (
    id integer NOT NULL,
    name text NOT NULL,
    "fk_Nations" integer NOT NULL,
    power integer NOT NULL,
    agenda text NOT NULL,
    contentment integer NOT NULL,
    color text NOT NULL,
    description text
);


--
-- Name: factions_id_seq; Type: SEQUENCE; Schema: game_1; Owner: -
--

ALTER TABLE game_1.factions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.factions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: localisations; Type: TABLE; Schema: game_1; Owner: -
--

CREATE TABLE game_1.localisations (
    id integer NOT NULL,
    name text NOT NULL,
    size integer NOT NULL,
    fortifications integer NOT NULL,
    fk_nations integer NOT NULL
);


--
-- Name: localisationsResources; Type: TABLE; Schema: game_1; Owner: -
--

CREATE TABLE game_1."localisationsResources" (
    id integer NOT NULL,
    fk_localisations integer NOT NULL,
    "fk_Resources" integer NOT NULL,
    amount double precision NOT NULL
);


--
-- Name: localisationsResources_id_seq; Type: SEQUENCE; Schema: game_1; Owner: -
--

ALTER TABLE game_1."localisationsResources" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1."localisationsResources_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: localisations_id_seq; Type: SEQUENCE; Schema: game_1; Owner: -
--

ALTER TABLE game_1.localisations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.localisations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: maintenanceCosts; Type: TABLE; Schema: game_1; Owner: -
--

CREATE TABLE game_1."maintenanceCosts" (
    id integer NOT NULL,
    "fk_UnitTypes" integer NOT NULL,
    "fk_Resources" integer NOT NULL,
    amount double precision NOT NULL
);


--
-- Name: maintenanceCosts_id_seq; Type: SEQUENCE; Schema: game_1; Owner: -
--

ALTER TABLE game_1."maintenanceCosts" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1."maintenanceCosts_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: map; Type: TABLE; Schema: game_1; Owner: -
--

CREATE TABLE game_1.map (
    id integer NOT NULL,
    name text NOT NULL,
    "mapLocation" text NOT NULL,
    "mapIconLocation" text NOT NULL
);


--
-- Name: mapAccess; Type: TABLE; Schema: game_1; Owner: -
--

CREATE TABLE game_1."mapAccess" (
    "fk_Nations" integer NOT NULL,
    "fk_Maps" integer NOT NULL
);


--
-- Name: map_id_seq; Type: SEQUENCE; Schema: game_1; Owner: -
--

ALTER TABLE game_1.map ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.map_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: modifiers; Type: TABLE; Schema: game_1; Owner: -
--

CREATE TABLE game_1.modifiers (
    id integer NOT NULL,
    event_id integer NOT NULL,
    modifier_type integer NOT NULL,
    effects jsonb NOT NULL
);


--
-- Name: modifiers_id_seq; Type: SEQUENCE; Schema: game_1; Owner: -
--

CREATE SEQUENCE game_1.modifiers_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: modifiers_id_seq; Type: SEQUENCE OWNED BY; Schema: game_1; Owner: -
--

ALTER SEQUENCE game_1.modifiers_id_seq OWNED BY game_1.modifiers.id;


--
-- Name: nations; Type: TABLE; Schema: game_1; Owner: -
--

CREATE TABLE game_1.nations (
    id integer NOT NULL,
    name text NOT NULL,
    fk_religions integer NOT NULL,
    fk_cultures integer NOT NULL,
    flag text,
    color text
);


--
-- Name: nations_id_seq; Type: SEQUENCE; Schema: game_1; Owner: -
--

ALTER TABLE game_1.nations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.nations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: offeredresources; Type: TABLE; Schema: game_1; Owner: -
--

CREATE TABLE game_1.offeredresources (
    id integer NOT NULL,
    fk_resource integer NOT NULL,
    fk_tradeagreement integer NOT NULL,
    quantity integer NOT NULL
);


--
-- Name: offeredresources_id_seq; Type: SEQUENCE; Schema: game_1; Owner: -
--

ALTER TABLE game_1.offeredresources ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.offeredresources_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ownedResources; Type: TABLE; Schema: game_1; Owner: -
--

CREATE TABLE game_1."ownedResources" (
    id integer NOT NULL,
    fk_nation integer NOT NULL,
    fk_resource integer NOT NULL,
    amount real DEFAULT 0 NOT NULL
);


--
-- Name: ownedResources_Id_seq; Type: SEQUENCE; Schema: game_1; Owner: -
--

CREATE SEQUENCE game_1."ownedResources_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: ownedResources_Id_seq; Type: SEQUENCE OWNED BY; Schema: game_1; Owner: -
--

ALTER SEQUENCE game_1."ownedResources_Id_seq" OWNED BY game_1."ownedResources".id;


--
-- Name: players; Type: TABLE; Schema: game_1; Owner: -
--

CREATE TABLE game_1.players (
    id integer NOT NULL,
    "fk_User" integer NOT NULL,
    "playerType" integer NOT NULL,
    name text NOT NULL
);


--
-- Name: players_id_seq; Type: SEQUENCE; Schema: game_1; Owner: -
--

ALTER TABLE game_1.players ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.players_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: populationproductionshares; Type: TABLE; Schema: game_1; Owner: -
--

CREATE TABLE game_1.populationproductionshares (
    id integer NOT NULL,
    fk_population integer NOT NULL,
    fk_resources integer NOT NULL,
    coefficient double precision NOT NULL
);


--
-- Name: populationproductionshares_id_seq; Type: SEQUENCE; Schema: game_1; Owner: -
--

ALTER TABLE game_1.populationproductionshares ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME game_1.populationproductionshares_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: populations; Type: TABLE; Schema: game_1; Owner: -
--

CREATE TABLE game_1.populations (
    id integer NOT NULL,
    fk_religions integer NOT NULL,
    fk_cultures integer NOT NULL,
    fk_socialgroups integer NOT NULL,
    fk_localisations integer NOT NULL,
    happiness real NOT NULL,
    volunteers integer
);


--
-- Name: populations_id_seq; Type: SEQUENCE; Schema: game_1; Owner: -
--

ALTER TABLE game_1.populations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.populations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: populationusedresource; Type: TABLE; Schema: game_1; Owner: -
--

CREATE TABLE game_1.populationusedresource (
    id integer NOT NULL,
    fk_population integer NOT NULL,
    fk_resources integer NOT NULL,
    amount double precision NOT NULL
);


--
-- Name: populationusedresource_id_seq; Type: SEQUENCE; Schema: game_1; Owner: -
--

ALTER TABLE game_1.populationusedresource ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME game_1.populationusedresource_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: productionCost; Type: TABLE; Schema: game_1; Owner: -
--

CREATE TABLE game_1."productionCost" (
    id integer NOT NULL,
    "fk_UnitTypes" integer NOT NULL,
    "fk_Resources" integer NOT NULL,
    amount double precision NOT NULL
);


--
-- Name: productionCost_id_seq; Type: SEQUENCE; Schema: game_1; Owner: -
--

ALTER TABLE game_1."productionCost" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1."productionCost_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: productionShares; Type: TABLE; Schema: game_1; Owner: -
--

CREATE TABLE game_1."productionShares" (
    id integer NOT NULL,
    "fk_SocialGroups" integer NOT NULL,
    "fk_Resources" integer NOT NULL,
    coefficient double precision NOT NULL
);


--
-- Name: productionShares_id_seq; Type: SEQUENCE; Schema: game_1; Owner: -
--

ALTER TABLE game_1."productionShares" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1."productionShares_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: relatedEvents; Type: TABLE; Schema: game_1; Owner: -
--

CREATE TABLE game_1."relatedEvents" (
    id integer NOT NULL,
    "fk_Events" integer NOT NULL,
    "fk_Nations" integer NOT NULL
);


--
-- Name: relatedEvents_id_seq; Type: SEQUENCE; Schema: game_1; Owner: -
--

ALTER TABLE game_1."relatedEvents" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1."relatedEvents_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: religions; Type: TABLE; Schema: game_1; Owner: -
--

CREATE TABLE game_1.religions (
    id integer NOT NULL,
    name text NOT NULL,
    icon text
);


--
-- Name: religions_id_seq; Type: SEQUENCE; Schema: game_1; Owner: -
--

ALTER TABLE game_1.religions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.religions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: resources; Type: TABLE; Schema: game_1; Owner: -
--

CREATE TABLE game_1.resources (
    id integer NOT NULL,
    name text NOT NULL,
    ismain boolean NOT NULL,
    icon text
);


--
-- Name: resources_id_seq; Type: SEQUENCE; Schema: game_1; Owner: -
--

ALTER TABLE game_1.resources ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.resources_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: socialgroups; Type: TABLE; Schema: game_1; Owner: -
--

CREATE TABLE game_1.socialgroups (
    id integer NOT NULL,
    name text NOT NULL,
    basehappiness real NOT NULL,
    volunteers integer NOT NULL,
    icon text
);


--
-- Name: socialgroups_id_seq; Type: SEQUENCE; Schema: game_1; Owner: -
--

ALTER TABLE game_1.socialgroups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.socialgroups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tradeagreements; Type: TABLE; Schema: game_1; Owner: -
--

CREATE TABLE game_1.tradeagreements (
    id integer NOT NULL,
    fk_nationoffering integer NOT NULL,
    fk_nationreceiving integer NOT NULL,
    status integer NOT NULL,
    duration integer NOT NULL,
    description text NOT NULL
);


--
-- Name: tradeagreements_id_seq; Type: SEQUENCE; Schema: game_1; Owner: -
--

ALTER TABLE game_1.tradeagreements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.tradeagreements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: troops; Type: TABLE; Schema: game_1; Owner: -
--

CREATE TABLE game_1.troops (
    id integer NOT NULL,
    "fk_UnitTypes" integer NOT NULL,
    "fk_Armies" integer NOT NULL,
    quantity integer NOT NULL
);


--
-- Name: troops_id_seq; Type: SEQUENCE; Schema: game_1; Owner: -
--

ALTER TABLE game_1.troops ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.troops_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: unitOrders; Type: TABLE; Schema: game_1; Owner: -
--

CREATE TABLE game_1."unitOrders" (
    id integer NOT NULL,
    "fk_UnitTypes" integer NOT NULL,
    "fk_Nations" integer NOT NULL,
    quantity integer NOT NULL
);


--
-- Name: unitOrders_id_seq; Type: SEQUENCE; Schema: game_1; Owner: -
--

ALTER TABLE game_1."unitOrders" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1."unitOrders_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: unitTypes; Type: TABLE; Schema: game_1; Owner: -
--

CREATE TABLE game_1."unitTypes" (
    id integer NOT NULL,
    name text NOT NULL,
    description text NOT NULL,
    melee integer NOT NULL,
    range integer NOT NULL,
    defense integer NOT NULL,
    speed integer NOT NULL,
    morale integer NOT NULL,
    "volunteersNeeded" integer NOT NULL,
    "isNaval" boolean NOT NULL
);


--
-- Name: unitTypes_id_seq; Type: SEQUENCE; Schema: game_1; Owner: -
--

ALTER TABLE game_1."unitTypes" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1."unitTypes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usedResources; Type: TABLE; Schema: game_1; Owner: -
--

CREATE TABLE game_1."usedResources" (
    id integer NOT NULL,
    "fk_SocialGroups" integer NOT NULL,
    "fk_Resources" integer NOT NULL,
    amount double precision NOT NULL
);


--
-- Name: usedResources_id_seq; Type: SEQUENCE; Schema: game_1; Owner: -
--

ALTER TABLE game_1."usedResources" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1."usedResources_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wantedresources; Type: TABLE; Schema: game_1; Owner: -
--

CREATE TABLE game_1.wantedresources (
    id integer NOT NULL,
    fk_resource integer NOT NULL,
    fk_tradeagreement integer NOT NULL,
    amount double precision NOT NULL
);


--
-- Name: wantedresources_id_seq; Type: SEQUENCE; Schema: game_1; Owner: -
--

ALTER TABLE game_1.wantedresources ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.wantedresources_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: modifiers id; Type: DEFAULT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1.modifiers ALTER COLUMN id SET DEFAULT nextval('game_1.modifiers_id_seq'::regclass);


--
-- Name: ownedResources id; Type: DEFAULT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1."ownedResources" ALTER COLUMN id SET DEFAULT nextval('game_1."ownedResources_Id_seq"'::regclass);


--
-- Name: accessToUnits PK_accessToUnits; Type: CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1."accessToUnits"
    ADD CONSTRAINT "PK_accessToUnits" PRIMARY KEY (id);


--
-- Name: accessestonations PK_accessestonations; Type: CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1.accessestonations
    ADD CONSTRAINT "PK_accessestonations" PRIMARY KEY (id);


--
-- Name: actions PK_actions; Type: CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1.actions
    ADD CONSTRAINT "PK_actions" PRIMARY KEY (id);


--
-- Name: armies PK_armies; Type: CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1.armies
    ADD CONSTRAINT "PK_armies" PRIMARY KEY (id);


--
-- Name: cultures PK_cultures; Type: CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1.cultures
    ADD CONSTRAINT "PK_cultures" PRIMARY KEY (id);


--
-- Name: events PK_events; Type: CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1.events
    ADD CONSTRAINT "PK_events" PRIMARY KEY (id);


--
-- Name: factions PK_factions; Type: CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1.factions
    ADD CONSTRAINT "PK_factions" PRIMARY KEY (id);


--
-- Name: localisations PK_localisations; Type: CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1.localisations
    ADD CONSTRAINT "PK_localisations" PRIMARY KEY (id);


--
-- Name: localisationsResources PK_localisationsResources; Type: CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1."localisationsResources"
    ADD CONSTRAINT "PK_localisationsResources" PRIMARY KEY (id);


--
-- Name: maintenanceCosts PK_maintenanceCosts; Type: CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1."maintenanceCosts"
    ADD CONSTRAINT "PK_maintenanceCosts" PRIMARY KEY (id);


--
-- Name: map PK_map; Type: CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1.map
    ADD CONSTRAINT "PK_map" PRIMARY KEY (id);


--
-- Name: mapAccess PK_mapAccess; Type: CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1."mapAccess"
    ADD CONSTRAINT "PK_mapAccess" PRIMARY KEY ("fk_Nations", "fk_Maps");


--
-- Name: nations PK_nations; Type: CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1.nations
    ADD CONSTRAINT "PK_nations" PRIMARY KEY (id);


--
-- Name: offeredresources PK_offeredresources; Type: CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1.offeredresources
    ADD CONSTRAINT "PK_offeredresources" PRIMARY KEY (id);


--
-- Name: players PK_players; Type: CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1.players
    ADD CONSTRAINT "PK_players" PRIMARY KEY (id);


--
-- Name: populations PK_populations; Type: CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1.populations
    ADD CONSTRAINT "PK_populations" PRIMARY KEY (id);


--
-- Name: productionCost PK_productionCost; Type: CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1."productionCost"
    ADD CONSTRAINT "PK_productionCost" PRIMARY KEY (id);


--
-- Name: productionShares PK_productionShares; Type: CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1."productionShares"
    ADD CONSTRAINT "PK_productionShares" PRIMARY KEY (id);


--
-- Name: relatedEvents PK_relatedEvents; Type: CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1."relatedEvents"
    ADD CONSTRAINT "PK_relatedEvents" PRIMARY KEY (id);


--
-- Name: religions PK_religions; Type: CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1.religions
    ADD CONSTRAINT "PK_religions" PRIMARY KEY (id);


--
-- Name: resources PK_resources; Type: CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1.resources
    ADD CONSTRAINT "PK_resources" PRIMARY KEY (id);


--
-- Name: socialgroups PK_socialgroups; Type: CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1.socialgroups
    ADD CONSTRAINT "PK_socialgroups" PRIMARY KEY (id);


--
-- Name: tradeagreements PK_tradeagreements; Type: CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1.tradeagreements
    ADD CONSTRAINT "PK_tradeagreements" PRIMARY KEY (id);


--
-- Name: troops PK_troops; Type: CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1.troops
    ADD CONSTRAINT "PK_troops" PRIMARY KEY (id);


--
-- Name: unitOrders PK_unitOrders; Type: CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1."unitOrders"
    ADD CONSTRAINT "PK_unitOrders" PRIMARY KEY (id);


--
-- Name: unitTypes PK_unitTypes; Type: CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1."unitTypes"
    ADD CONSTRAINT "PK_unitTypes" PRIMARY KEY (id);


--
-- Name: usedResources PK_usedResources; Type: CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1."usedResources"
    ADD CONSTRAINT "PK_usedResources" PRIMARY KEY (id);


--
-- Name: wantedresources PK_wantedresources; Type: CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1.wantedresources
    ADD CONSTRAINT "PK_wantedresources" PRIMARY KEY (id);


--
-- Name: modifiers modifiers_pkey; Type: CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1.modifiers
    ADD CONSTRAINT modifiers_pkey PRIMARY KEY (id);


--
-- Name: ownedResources ownedResources_pkey; Type: CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1."ownedResources"
    ADD CONSTRAINT "ownedResources_pkey" PRIMARY KEY (id);


--
-- Name: populationproductionshares populationproductionshares_pkey; Type: CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1.populationproductionshares
    ADD CONSTRAINT populationproductionshares_pkey PRIMARY KEY (id);


--
-- Name: populationusedresource populationusedresource_pkey; Type: CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1.populationusedresource
    ADD CONSTRAINT populationusedresource_pkey PRIMARY KEY (id);


--
-- Name: IX_accessToUnits_fk_Nations; Type: INDEX; Schema: game_1; Owner: -
--

CREATE INDEX "IX_accessToUnits_fk_Nations" ON game_1."accessToUnits" USING btree ("fk_Nation");


--
-- Name: IX_accessToUnits_fk_UnitTypes; Type: INDEX; Schema: game_1; Owner: -
--

CREATE INDEX "IX_accessToUnits_fk_UnitTypes" ON game_1."accessToUnits" USING btree ("fk_UnitTypes");


--
-- Name: IX_accessestonations_fk_nations; Type: INDEX; Schema: game_1; Owner: -
--

CREATE INDEX "IX_accessestonations_fk_nations" ON game_1.accessestonations USING btree (fk_nations);


--
-- Name: IX_accessestonations_fk_users; Type: INDEX; Schema: game_1; Owner: -
--

CREATE INDEX "IX_accessestonations_fk_users" ON game_1.accessestonations USING btree (fk_users);


--
-- Name: IX_actions_fk_Nations; Type: INDEX; Schema: game_1; Owner: -
--

CREATE INDEX "IX_actions_fk_Nations" ON game_1.actions USING btree ("fk_Nations");


--
-- Name: IX_armies_fk_Nations; Type: INDEX; Schema: game_1; Owner: -
--

CREATE INDEX "IX_armies_fk_Nations" ON game_1.armies USING btree ("fk_Nations");


--
-- Name: IX_armies_fk_localisations; Type: INDEX; Schema: game_1; Owner: -
--

CREATE INDEX "IX_armies_fk_localisations" ON game_1.armies USING btree (fk_localisations);


--
-- Name: IX_factions_fk_Nations; Type: INDEX; Schema: game_1; Owner: -
--

CREATE INDEX "IX_factions_fk_Nations" ON game_1.factions USING btree ("fk_Nations");


--
-- Name: IX_localisations_fk_nations; Type: INDEX; Schema: game_1; Owner: -
--

CREATE INDEX "IX_localisations_fk_nations" ON game_1.localisations USING btree (fk_nations);


--
-- Name: IX_maintenanceCosts_fk_Resources; Type: INDEX; Schema: game_1; Owner: -
--

CREATE INDEX "IX_maintenanceCosts_fk_Resources" ON game_1."maintenanceCosts" USING btree ("fk_Resources");


--
-- Name: IX_maintenanceCosts_fk_UnitTypes; Type: INDEX; Schema: game_1; Owner: -
--

CREATE INDEX "IX_maintenanceCosts_fk_UnitTypes" ON game_1."maintenanceCosts" USING btree ("fk_UnitTypes");


--
-- Name: IX_mapAccess_fk_Maps; Type: INDEX; Schema: game_1; Owner: -
--

CREATE INDEX "IX_mapAccess_fk_Maps" ON game_1."mapAccess" USING btree ("fk_Maps");


--
-- Name: IX_offeredresources_fk_resource; Type: INDEX; Schema: game_1; Owner: -
--

CREATE INDEX "IX_offeredresources_fk_resource" ON game_1.offeredresources USING btree (fk_resource);


--
-- Name: IX_offeredresources_fk_tradeagreement; Type: INDEX; Schema: game_1; Owner: -
--

CREATE INDEX "IX_offeredresources_fk_tradeagreement" ON game_1.offeredresources USING btree (fk_tradeagreement);


--
-- Name: IX_populations_fk_cultures; Type: INDEX; Schema: game_1; Owner: -
--

CREATE INDEX "IX_populations_fk_cultures" ON game_1.populations USING btree (fk_cultures);


--
-- Name: IX_populations_fk_localisations; Type: INDEX; Schema: game_1; Owner: -
--

CREATE INDEX "IX_populations_fk_localisations" ON game_1.populations USING btree (fk_localisations);


--
-- Name: IX_populations_fk_religions; Type: INDEX; Schema: game_1; Owner: -
--

CREATE INDEX "IX_populations_fk_religions" ON game_1.populations USING btree (fk_religions);


--
-- Name: IX_populations_fk_socialgroups; Type: INDEX; Schema: game_1; Owner: -
--

CREATE INDEX "IX_populations_fk_socialgroups" ON game_1.populations USING btree (fk_socialgroups);


--
-- Name: IX_productionCost_fk_Resources; Type: INDEX; Schema: game_1; Owner: -
--

CREATE INDEX "IX_productionCost_fk_Resources" ON game_1."productionCost" USING btree ("fk_Resources");


--
-- Name: IX_productionCost_fk_UnitTypes; Type: INDEX; Schema: game_1; Owner: -
--

CREATE INDEX "IX_productionCost_fk_UnitTypes" ON game_1."productionCost" USING btree ("fk_UnitTypes");


--
-- Name: IX_relatedEvents_fk_Events; Type: INDEX; Schema: game_1; Owner: -
--

CREATE INDEX "IX_relatedEvents_fk_Events" ON game_1."relatedEvents" USING btree ("fk_Events");


--
-- Name: IX_relatedEvents_fk_Nations; Type: INDEX; Schema: game_1; Owner: -
--

CREATE INDEX "IX_relatedEvents_fk_Nations" ON game_1."relatedEvents" USING btree ("fk_Nations");


--
-- Name: IX_tradeagreements_fk_nationoffering; Type: INDEX; Schema: game_1; Owner: -
--

CREATE INDEX "IX_tradeagreements_fk_nationoffering" ON game_1.tradeagreements USING btree (fk_nationoffering);


--
-- Name: IX_tradeagreements_fk_nationreceiving; Type: INDEX; Schema: game_1; Owner: -
--

CREATE INDEX "IX_tradeagreements_fk_nationreceiving" ON game_1.tradeagreements USING btree (fk_nationreceiving);


--
-- Name: IX_troops_fk_Armies; Type: INDEX; Schema: game_1; Owner: -
--

CREATE INDEX "IX_troops_fk_Armies" ON game_1.troops USING btree ("fk_Armies");


--
-- Name: IX_troops_fk_UnitTypes; Type: INDEX; Schema: game_1; Owner: -
--

CREATE INDEX "IX_troops_fk_UnitTypes" ON game_1.troops USING btree ("fk_UnitTypes");


--
-- Name: IX_unitOrders_fk_Nations; Type: INDEX; Schema: game_1; Owner: -
--

CREATE INDEX "IX_unitOrders_fk_Nations" ON game_1."unitOrders" USING btree ("fk_Nations");


--
-- Name: IX_unitOrders_fk_UnitTypes; Type: INDEX; Schema: game_1; Owner: -
--

CREATE INDEX "IX_unitOrders_fk_UnitTypes" ON game_1."unitOrders" USING btree ("fk_UnitTypes");


--
-- Name: IX_wantedresources_fk_resource; Type: INDEX; Schema: game_1; Owner: -
--

CREATE INDEX "IX_wantedresources_fk_resource" ON game_1.wantedresources USING btree (fk_resource);


--
-- Name: IX_wantedresources_fk_tradeagreement; Type: INDEX; Schema: game_1; Owner: -
--

CREATE INDEX "IX_wantedresources_fk_tradeagreement" ON game_1.wantedresources USING btree (fk_tradeagreement);


--
-- Name: nations trg_after_nations_insert; Type: TRIGGER; Schema: game_1; Owner: -
--

CREATE TRIGGER trg_after_nations_insert AFTER INSERT ON game_1.nations FOR EACH ROW EXECUTE FUNCTION game_1.add_nation_to_all_resources();


--
-- Name: populations trg_after_populations_insert; Type: TRIGGER; Schema: game_1; Owner: -
--

CREATE TRIGGER trg_after_populations_insert AFTER INSERT ON game_1.populations FOR EACH ROW EXECUTE FUNCTION game_1.add_population_relations();


--
-- Name: productionShares trg_after_productionshares_insert; Type: TRIGGER; Schema: game_1; Owner: -
--

CREATE TRIGGER trg_after_productionshares_insert AFTER INSERT ON game_1."productionShares" FOR EACH ROW EXECUTE FUNCTION game_1.add_production_shares_to_populations();


--
-- Name: resources trg_after_resources_insert; Type: TRIGGER; Schema: game_1; Owner: -
--

CREATE TRIGGER trg_after_resources_insert AFTER INSERT ON game_1.resources FOR EACH ROW EXECUTE FUNCTION game_1.add_resource_to_all_nations();


--
-- Name: usedResources trg_after_usedresources_insert; Type: TRIGGER; Schema: game_1; Owner: -
--

CREATE TRIGGER trg_after_usedresources_insert AFTER INSERT ON game_1."usedResources" FOR EACH ROW EXECUTE FUNCTION game_1.add_used_resources_to_populations();


--
-- Name: accessToUnits FK_accessToUnits_fk_Nations; Type: FK CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1."accessToUnits"
    ADD CONSTRAINT "FK_accessToUnits_fk_Nations" FOREIGN KEY ("fk_Nation") REFERENCES game_1.nations(id) ON DELETE RESTRICT;


--
-- Name: accessToUnits FK_accessToUnits_fk_UnitTypes; Type: FK CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1."accessToUnits"
    ADD CONSTRAINT "FK_accessToUnits_fk_UnitTypes" FOREIGN KEY ("fk_UnitTypes") REFERENCES game_1."unitTypes"(id) ON DELETE CASCADE;


--
-- Name: accessestonations FK_accessestonations_fk_nations; Type: FK CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1.accessestonations
    ADD CONSTRAINT "FK_accessestonations_fk_nations" FOREIGN KEY (fk_nations) REFERENCES game_1.nations(id) ON DELETE CASCADE;


--
-- Name: accessestonations FK_accessestonations_fk_users; Type: FK CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1.accessestonations
    ADD CONSTRAINT "FK_accessestonations_fk_users" FOREIGN KEY (fk_users) REFERENCES game_1.players(id) ON DELETE CASCADE;


--
-- Name: actions FK_actions_fk_Nations; Type: FK CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1.actions
    ADD CONSTRAINT "FK_actions_fk_Nations" FOREIGN KEY ("fk_Nations") REFERENCES game_1.nations(id) ON DELETE RESTRICT;


--
-- Name: armies FK_armies_localisations_fk_localisations; Type: FK CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1.armies
    ADD CONSTRAINT "FK_armies_localisations_fk_localisations" FOREIGN KEY (fk_localisations) REFERENCES game_1.localisations(id) ON DELETE CASCADE;


--
-- Name: armies FK_armies_nations_fk_Nations; Type: FK CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1.armies
    ADD CONSTRAINT "FK_armies_nations_fk_Nations" FOREIGN KEY ("fk_Nations") REFERENCES game_1.nations(id) ON DELETE RESTRICT;


--
-- Name: factions FK_factions_fk_Nations; Type: FK CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1.factions
    ADD CONSTRAINT "FK_factions_fk_Nations" FOREIGN KEY ("fk_Nations") REFERENCES game_1.nations(id) ON DELETE RESTRICT;


--
-- Name: localisationsResources FK_localisationsResources_localisations_fk_localisations; Type: FK CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1."localisationsResources"
    ADD CONSTRAINT "FK_localisationsResources_localisations_fk_localisations" FOREIGN KEY (fk_localisations) REFERENCES game_1.localisations(id) ON DELETE CASCADE;


--
-- Name: localisationsResources FK_localisationsResources_resources_fk_Resources; Type: FK CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1."localisationsResources"
    ADD CONSTRAINT "FK_localisationsResources_resources_fk_Resources" FOREIGN KEY ("fk_Resources") REFERENCES game_1.resources(id) ON DELETE CASCADE;


--
-- Name: localisations FK_localisations_nations_fk_nations; Type: FK CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1.localisations
    ADD CONSTRAINT "FK_localisations_nations_fk_nations" FOREIGN KEY (fk_nations) REFERENCES game_1.nations(id) ON DELETE RESTRICT;


--
-- Name: maintenanceCosts FK_maintenanceCosts_fk_Resources; Type: FK CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1."maintenanceCosts"
    ADD CONSTRAINT "FK_maintenanceCosts_fk_Resources" FOREIGN KEY ("fk_Resources") REFERENCES game_1.resources(id) ON DELETE CASCADE;


--
-- Name: maintenanceCosts FK_maintenanceCosts_fk_UnitTypes; Type: FK CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1."maintenanceCosts"
    ADD CONSTRAINT "FK_maintenanceCosts_fk_UnitTypes" FOREIGN KEY ("fk_UnitTypes") REFERENCES game_1."unitTypes"(id) ON DELETE CASCADE;


--
-- Name: mapAccess FK_mapAccess_map_fk_Maps; Type: FK CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1."mapAccess"
    ADD CONSTRAINT "FK_mapAccess_map_fk_Maps" FOREIGN KEY ("fk_Maps") REFERENCES game_1.map(id) ON DELETE CASCADE;


--
-- Name: mapAccess FK_mapAccess_map_fk_Nation; Type: FK CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1."mapAccess"
    ADD CONSTRAINT "FK_mapAccess_map_fk_Nation" FOREIGN KEY ("fk_Nations") REFERENCES game_1.nations(id) ON DELETE CASCADE;


--
-- Name: nations FK_nations_players_fk_cultures; Type: FK CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1.nations
    ADD CONSTRAINT "FK_nations_players_fk_cultures" FOREIGN KEY (fk_cultures) REFERENCES game_1.cultures(id) ON DELETE CASCADE;


--
-- Name: nations FK_nations_players_fk_religions; Type: FK CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1.nations
    ADD CONSTRAINT "FK_nations_players_fk_religions" FOREIGN KEY (fk_religions) REFERENCES game_1.religions(id) ON DELETE RESTRICT;


--
-- Name: offeredresources FK_offeredresources_resources_fk_resource; Type: FK CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1.offeredresources
    ADD CONSTRAINT "FK_offeredresources_resources_fk_resource" FOREIGN KEY (fk_resource) REFERENCES game_1.resources(id) ON DELETE CASCADE;


--
-- Name: offeredresources FK_offeredresources_tradeagreements_fk_tradeagreement; Type: FK CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1.offeredresources
    ADD CONSTRAINT "FK_offeredresources_tradeagreements_fk_tradeagreement" FOREIGN KEY (fk_tradeagreement) REFERENCES game_1.tradeagreements(id) ON DELETE CASCADE;


--
-- Name: ownedResources FK_ownedresources_nation_fk_nation; Type: FK CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1."ownedResources"
    ADD CONSTRAINT "FK_ownedresources_nation_fk_nation" FOREIGN KEY (fk_nation) REFERENCES game_1.nations(id) ON DELETE RESTRICT;


--
-- Name: ownedResources FK_ownedresources_resource_fk_resource; Type: FK CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1."ownedResources"
    ADD CONSTRAINT "FK_ownedresources_resource_fk_resource" FOREIGN KEY (fk_resource) REFERENCES game_1.resources(id) ON DELETE CASCADE;


--
-- Name: players FK_players_users_fk_users; Type: FK CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1.players
    ADD CONSTRAINT "FK_players_users_fk_users" FOREIGN KEY ("fk_User") REFERENCES "Global".users(id) ON DELETE CASCADE;


--
-- Name: populations FK_populations_cultures_fk_cultures; Type: FK CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1.populations
    ADD CONSTRAINT "FK_populations_cultures_fk_cultures" FOREIGN KEY (fk_cultures) REFERENCES game_1.cultures(id) ON DELETE CASCADE;


--
-- Name: populations FK_populations_localisations_fk_localisations; Type: FK CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1.populations
    ADD CONSTRAINT "FK_populations_localisations_fk_localisations" FOREIGN KEY (fk_localisations) REFERENCES game_1.localisations(id) ON DELETE CASCADE;


--
-- Name: populations FK_populations_religions_fk_religions; Type: FK CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1.populations
    ADD CONSTRAINT "FK_populations_religions_fk_religions" FOREIGN KEY (fk_religions) REFERENCES game_1.religions(id) ON DELETE RESTRICT;


--
-- Name: populations FK_populations_socialgroups_fk_socialgroups; Type: FK CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1.populations
    ADD CONSTRAINT "FK_populations_socialgroups_fk_socialgroups" FOREIGN KEY (fk_socialgroups) REFERENCES game_1.socialgroups(id) ON DELETE CASCADE;


--
-- Name: productionCost FK_productionCost_resources_fk_Resources; Type: FK CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1."productionCost"
    ADD CONSTRAINT "FK_productionCost_resources_fk_Resources" FOREIGN KEY ("fk_Resources") REFERENCES game_1.resources(id) ON DELETE CASCADE;


--
-- Name: productionCost FK_productionCost_unitTypes_fk_UnitTypes; Type: FK CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1."productionCost"
    ADD CONSTRAINT "FK_productionCost_unitTypes_fk_UnitTypes" FOREIGN KEY ("fk_UnitTypes") REFERENCES game_1."unitTypes"(id) ON DELETE CASCADE;


--
-- Name: productionShares FK_productionShares_populations_fk_Resources; Type: FK CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1."productionShares"
    ADD CONSTRAINT "FK_productionShares_populations_fk_Resources" FOREIGN KEY ("fk_Resources") REFERENCES game_1.resources(id) ON DELETE CASCADE;


--
-- Name: productionShares FK_productionShares_populations_fk_SocialGroups; Type: FK CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1."productionShares"
    ADD CONSTRAINT "FK_productionShares_populations_fk_SocialGroups" FOREIGN KEY ("fk_SocialGroups") REFERENCES game_1.socialgroups(id) ON DELETE CASCADE;


--
-- Name: relatedEvents FK_relatedEvents_events_fk_Events; Type: FK CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1."relatedEvents"
    ADD CONSTRAINT "FK_relatedEvents_events_fk_Events" FOREIGN KEY ("fk_Events") REFERENCES game_1.events(id) ON DELETE CASCADE;


--
-- Name: relatedEvents FK_relatedEvents_nations_fk_Nations; Type: FK CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1."relatedEvents"
    ADD CONSTRAINT "FK_relatedEvents_nations_fk_Nations" FOREIGN KEY ("fk_Nations") REFERENCES game_1.nations(id) ON DELETE RESTRICT;


--
-- Name: tradeagreements FK_tradeagreements_nations_fk_nationoffering; Type: FK CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1.tradeagreements
    ADD CONSTRAINT "FK_tradeagreements_nations_fk_nationoffering" FOREIGN KEY (fk_nationoffering) REFERENCES game_1.nations(id) ON DELETE RESTRICT;


--
-- Name: tradeagreements FK_tradeagreements_nations_fk_nationreceiving; Type: FK CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1.tradeagreements
    ADD CONSTRAINT "FK_tradeagreements_nations_fk_nationreceiving" FOREIGN KEY (fk_nationreceiving) REFERENCES game_1.nations(id) ON DELETE RESTRICT;


--
-- Name: troops FK_troops_armies_fk_Armies; Type: FK CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1.troops
    ADD CONSTRAINT "FK_troops_armies_fk_Armies" FOREIGN KEY ("fk_Armies") REFERENCES game_1.armies(id) ON DELETE CASCADE;


--
-- Name: troops FK_troops_unitTypes_fk_UnitTypes; Type: FK CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1.troops
    ADD CONSTRAINT "FK_troops_unitTypes_fk_UnitTypes" FOREIGN KEY ("fk_UnitTypes") REFERENCES game_1."unitTypes"(id) ON DELETE CASCADE;


--
-- Name: unitOrders FK_unitOrders_nations_fk_Nations; Type: FK CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1."unitOrders"
    ADD CONSTRAINT "FK_unitOrders_nations_fk_Nations" FOREIGN KEY ("fk_Nations") REFERENCES game_1.nations(id) ON DELETE RESTRICT;


--
-- Name: unitOrders FK_unitOrders_unitTypes_fk_UnitTypes; Type: FK CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1."unitOrders"
    ADD CONSTRAINT "FK_unitOrders_unitTypes_fk_UnitTypes" FOREIGN KEY ("fk_UnitTypes") REFERENCES game_1."unitTypes"(id) ON DELETE CASCADE;


--
-- Name: usedResources FK_usedResources_populations_fk_Resources; Type: FK CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1."usedResources"
    ADD CONSTRAINT "FK_usedResources_populations_fk_Resources" FOREIGN KEY ("fk_Resources") REFERENCES game_1.resources(id) ON DELETE CASCADE;


--
-- Name: usedResources FK_usedResources_populations_fk_SocialGroups; Type: FK CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1."usedResources"
    ADD CONSTRAINT "FK_usedResources_populations_fk_SocialGroups" FOREIGN KEY ("fk_SocialGroups") REFERENCES game_1.socialgroups(id) ON DELETE CASCADE;


--
-- Name: wantedresources FK_wantedresources_resources_fk_resource; Type: FK CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1.wantedresources
    ADD CONSTRAINT "FK_wantedresources_resources_fk_resource" FOREIGN KEY (fk_resource) REFERENCES game_1.resources(id) ON DELETE CASCADE;


--
-- Name: wantedresources FK_wantedresources_tradeagreements_fk_tradeagreement; Type: FK CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1.wantedresources
    ADD CONSTRAINT "FK_wantedresources_tradeagreements_fk_tradeagreement" FOREIGN KEY (fk_tradeagreement) REFERENCES game_1.tradeagreements(id) ON DELETE CASCADE;


--
-- Name: modifiers modifiers_event_id_fkey; Type: FK CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1.modifiers
    ADD CONSTRAINT modifiers_event_id_fkey FOREIGN KEY (event_id) REFERENCES game_1.events(id) ON DELETE CASCADE;


--
-- Name: populationproductionshares populationproductionshares_fkpopulation_fkey; Type: FK CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1.populationproductionshares
    ADD CONSTRAINT populationproductionshares_fkpopulation_fkey FOREIGN KEY (fk_population) REFERENCES game_1.populations(id) ON DELETE CASCADE;


--
-- Name: populationproductionshares populationproductionshares_fkresources_fkey; Type: FK CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1.populationproductionshares
    ADD CONSTRAINT populationproductionshares_fkresources_fkey FOREIGN KEY (fk_resources) REFERENCES game_1.resources(id) ON DELETE CASCADE;


--
-- Name: populationusedresource populationusedresource_fkpopulation_fkey; Type: FK CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1.populationusedresource
    ADD CONSTRAINT populationusedresource_fkpopulation_fkey FOREIGN KEY (fk_population) REFERENCES game_1.populations(id) ON DELETE CASCADE;


--
-- Name: populationusedresource populationusedresource_fkresources_fkey; Type: FK CONSTRAINT; Schema: game_1; Owner: -
--

ALTER TABLE ONLY game_1.populationusedresource
    ADD CONSTRAINT populationusedresource_fkresources_fkey FOREIGN KEY (fk_resources) REFERENCES game_1.resources(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

