--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: Global; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA "Global";


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: gameaccess; Type: TABLE; Schema: Global; Owner: -
--

CREATE TABLE "Global".gameaccess (
    id integer NOT NULL,
    "fk_Users" integer NOT NULL,
    "fk_Games" integer NOT NULL,
    "accessType" integer NOT NULL,
    "nationName" text,
    "isArchived" boolean NOT NULL
);


--
-- Name: gameaccess_id_seq; Type: SEQUENCE; Schema: Global; Owner: -
--

ALTER TABLE "Global".gameaccess ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Global".gameaccess_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: games; Type: TABLE; Schema: Global; Owner: -
--

CREATE TABLE "Global".games (
    id integer NOT NULL,
    name text NOT NULL,
    description text,
    image text,
    "ownerId" integer NOT NULL,
    game_code text DEFAULT upper(substr(md5((random())::text), 1, 6))
);


--
-- Name: games_id_seq; Type: SEQUENCE; Schema: Global; Owner: -
--

ALTER TABLE "Global".games ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Global".games_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: refresh_tokens; Type: TABLE; Schema: Global; Owner: -
--

CREATE TABLE "Global".refresh_tokens (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id integer,
    token text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now()
);


--
-- Name: users; Type: TABLE; Schema: Global; Owner: -
--

CREATE TABLE "Global".users (
    id integer NOT NULL,
    name text NOT NULL,
    email text NOT NULL,
    password text NOT NULL,
    issso boolean NOT NULL,
    isarchived boolean NOT NULL,
    image text
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: Global; Owner: -
--

ALTER TABLE "Global".users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Global".users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: gameaccess PK_gameaccess; Type: CONSTRAINT; Schema: Global; Owner: -
--

ALTER TABLE ONLY "Global".gameaccess
    ADD CONSTRAINT "PK_gameaccess" PRIMARY KEY ("fk_Users", "fk_Games");


--
-- Name: games PK_games; Type: CONSTRAINT; Schema: Global; Owner: -
--

ALTER TABLE ONLY "Global".games
    ADD CONSTRAINT "PK_games" PRIMARY KEY (id);


--
-- Name: users PK_users; Type: CONSTRAINT; Schema: Global; Owner: -
--

ALTER TABLE ONLY "Global".users
    ADD CONSTRAINT "PK_users" PRIMARY KEY (id);


--
-- Name: refresh_tokens refresh_tokens_pkey; Type: CONSTRAINT; Schema: Global; Owner: -
--

ALTER TABLE ONLY "Global".refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);


--
-- Name: IX_gameaccess_fk_Games; Type: INDEX; Schema: Global; Owner: -
--

CREATE INDEX "IX_gameaccess_fk_Games" ON "Global".gameaccess USING btree ("fk_Games");


--
-- Name: IX_games_name; Type: INDEX; Schema: Global; Owner: -
--

CREATE UNIQUE INDEX "IX_games_name" ON "Global".games USING btree (name);


--
-- Name: IX_games_ownerId; Type: INDEX; Schema: Global; Owner: -
--

CREATE INDEX "IX_games_ownerId" ON "Global".games USING btree ("ownerId");


--
-- Name: IX_users_email; Type: INDEX; Schema: Global; Owner: -
--

CREATE UNIQUE INDEX "IX_users_email" ON "Global".users USING btree (email);


--
-- Name: IX_users_name; Type: INDEX; Schema: Global; Owner: -
--

CREATE UNIQUE INDEX "IX_users_name" ON "Global".users USING btree (name);


--
-- Name: gameaccess FK_gameaccess_games_fk_Games; Type: FK CONSTRAINT; Schema: Global; Owner: -
--

ALTER TABLE ONLY "Global".gameaccess
    ADD CONSTRAINT "FK_gameaccess_games_fk_Games" FOREIGN KEY ("fk_Games") REFERENCES "Global".games(id) ON DELETE CASCADE;


--
-- Name: gameaccess FK_gameaccess_users_fk_Users; Type: FK CONSTRAINT; Schema: Global; Owner: -
--

ALTER TABLE ONLY "Global".gameaccess
    ADD CONSTRAINT "FK_gameaccess_users_fk_Users" FOREIGN KEY ("fk_Users") REFERENCES "Global".users(id) ON DELETE CASCADE;


--
-- Name: games FK_games_users_ownerId; Type: FK CONSTRAINT; Schema: Global; Owner: -
--

ALTER TABLE ONLY "Global".games
    ADD CONSTRAINT "FK_games_users_ownerId" FOREIGN KEY ("ownerId") REFERENCES "Global".users(id) ON DELETE CASCADE;


--
-- Name: refresh_tokens refresh_tokens_user_id_fkey; Type: FK CONSTRAINT; Schema: Global; Owner: -
--

ALTER TABLE ONLY "Global".refresh_tokens
    ADD CONSTRAINT refresh_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES "Global".users(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

