--
-- PostgreSQL database dump
--

\restrict 5Dd2IgwOLlIU84q20HYGYJsYgngmQacQLWJUFrgwJxjb9ubg417RqHoHYcgmKqO

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

-- Started on 2026-02-15 18:30:01

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 96082)
-- Name: gameaccess; Type: TABLE; Schema: Global; Owner: postgres
--

CREATE TABLE "Global".gameaccess (
    id integer NOT NULL,
    "fk_Users" integer NOT NULL,
    "fk_Games" integer NOT NULL,
    "accessType" integer NOT NULL,
    "isArchived" boolean NOT NULL,
    "nationName" text
);


ALTER TABLE "Global".gameaccess OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 96085)
-- Name: gameaccess_id_seq; Type: SEQUENCE; Schema: Global; Owner: postgres
--

ALTER TABLE "Global".gameaccess ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Global".gameaccess_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 96086)
-- Name: games; Type: TABLE; Schema: Global; Owner: postgres
--

CREATE TABLE "Global".games (
    id integer NOT NULL,
    name text NOT NULL,
    description text,
    image text,
    "ownerId" integer NOT NULL,
    game_code text DEFAULT upper(substr(md5((random())::text), 1, 6))
);


ALTER TABLE "Global".games OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 96092)
-- Name: games_id_seq; Type: SEQUENCE; Schema: Global; Owner: postgres
--

ALTER TABLE "Global".games ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Global".games_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 96093)
-- Name: refresh_tokens; Type: TABLE; Schema: Global; Owner: postgres
--

CREATE TABLE "Global".refresh_tokens (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id integer,
    token text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now()
);


ALTER TABLE "Global".refresh_tokens OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 96100)
-- Name: users; Type: TABLE; Schema: Global; Owner: postgres
--

CREATE TABLE "Global".users (
    id integer NOT NULL,
    name text NOT NULL,
    email text NOT NULL,
    password text NOT NULL,
    issso boolean NOT NULL,
    isarchived boolean NOT NULL,
    image text
);


ALTER TABLE "Global".users OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 96105)
-- Name: users_id_seq; Type: SEQUENCE; Schema: Global; Owner: postgres
--

ALTER TABLE "Global".users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Global".users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 96106)
-- Name: accessToUnits; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1."accessToUnits" (
    id integer NOT NULL,
    "fk_Nation" integer NOT NULL,
    "fk_UnitTypes" integer NOT NULL
);


ALTER TABLE game_1."accessToUnits" OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 96109)
-- Name: accessToUnits_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1."accessToUnits" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1."accessToUnits_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 96110)
-- Name: accessestonations; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1.accessestonations (
    id integer NOT NULL,
    fk_nations integer NOT NULL,
    fk_users integer NOT NULL,
    dateacquired timestamp with time zone NOT NULL,
    isactive boolean NOT NULL
);


ALTER TABLE game_1.accessestonations OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 96113)
-- Name: accessestonations_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1.accessestonations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.accessestonations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 96114)
-- Name: actions; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1.actions (
    id integer NOT NULL,
    "fk_Nations" integer NOT NULL,
    name text,
    description text NOT NULL,
    result text,
    "isSettled" boolean NOT NULL
);


ALTER TABLE game_1.actions OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 96119)
-- Name: actions_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1.actions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.actions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 96120)
-- Name: armies; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1.armies (
    id integer NOT NULL,
    name text NOT NULL,
    "fk_Nations" integer NOT NULL,
    fk_localisations integer,
    is_naval boolean NOT NULL
);


ALTER TABLE game_1.armies OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 96125)
-- Name: armies_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1.armies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.armies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 290 (class 1259 OID 96636)
-- Name: armySettings; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1."armySettings" (
    id integer NOT NULL,
    "nameOfSettingsSet" text,
    "useMeleeAtack" boolean DEFAULT true NOT NULL,
    "useRangeAtack" boolean DEFAULT true NOT NULL,
    "useDefense" boolean DEFAULT true NOT NULL,
    "useSpeed" boolean DEFAULT true NOT NULL,
    "useMorale" boolean DEFAULT true NOT NULL,
    "useMaintanace" boolean DEFAULT true NOT NULL
);


ALTER TABLE game_1."armySettings" OWNER TO postgres;

--
-- TOC entry 291 (class 1259 OID 96643)
-- Name: army_settings_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1."armySettings" ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME game_1.army_settings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 10000
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 96126)
-- Name: cultures; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1.cultures (
    id integer NOT NULL,
    name text NOT NULL
);


ALTER TABLE game_1.cultures OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 96131)
-- Name: cultures_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1.cultures ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.cultures_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 96132)
-- Name: events; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1.events (
    id integer NOT NULL,
    name text NOT NULL,
    description text,
    isactive boolean NOT NULL,
    picture text
);


ALTER TABLE game_1.events OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 96137)
-- Name: events_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1.events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 239 (class 1259 OID 96138)
-- Name: factions; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1.factions (
    id integer NOT NULL,
    name text NOT NULL,
    "fk_Nations" integer NOT NULL,
    power integer NOT NULL,
    agenda text NOT NULL,
    contentment integer NOT NULL,
    color text NOT NULL,
    description text
);


ALTER TABLE game_1.factions OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 96143)
-- Name: factions_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1.factions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.factions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 241 (class 1259 OID 96144)
-- Name: localisations; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1.localisations (
    id integer NOT NULL,
    name text NOT NULL,
    size integer NOT NULL,
    fortifications integer NOT NULL,
    fk_nations integer NOT NULL
);


ALTER TABLE game_1.localisations OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 96149)
-- Name: localisationsResources; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1."localisationsResources" (
    id integer NOT NULL,
    fk_localisations integer NOT NULL,
    "fk_Resources" integer NOT NULL,
    amount double precision NOT NULL
);


ALTER TABLE game_1."localisationsResources" OWNER TO postgres;

--
-- TOC entry 243 (class 1259 OID 96152)
-- Name: localisationsResources_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1."localisationsResources" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1."localisationsResources_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 244 (class 1259 OID 96153)
-- Name: localisations_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1.localisations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.localisations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 245 (class 1259 OID 96154)
-- Name: maintenanceCosts; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1."maintenanceCosts" (
    id integer NOT NULL,
    "fk_UnitTypes" integer NOT NULL,
    "fk_Resources" integer NOT NULL,
    amount double precision NOT NULL
);


ALTER TABLE game_1."maintenanceCosts" OWNER TO postgres;

--
-- TOC entry 246 (class 1259 OID 96157)
-- Name: maintenanceCosts_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1."maintenanceCosts" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1."maintenanceCosts_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 247 (class 1259 OID 96158)
-- Name: map; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1.map (
    id integer NOT NULL,
    name text NOT NULL,
    "mapLocation" text NOT NULL,
    "mapIconLocation" text NOT NULL
);


ALTER TABLE game_1.map OWNER TO postgres;

--
-- TOC entry 248 (class 1259 OID 96163)
-- Name: mapAccess; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1."mapAccess" (
    "fk_Nations" integer NOT NULL,
    "fk_Maps" integer NOT NULL
);


ALTER TABLE game_1."mapAccess" OWNER TO postgres;

--
-- TOC entry 249 (class 1259 OID 96166)
-- Name: map_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1.map ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.map_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 250 (class 1259 OID 96167)
-- Name: modifiers; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1.modifiers (
    id integer NOT NULL,
    event_id integer NOT NULL,
    modifier_type integer NOT NULL,
    effects jsonb NOT NULL
);


ALTER TABLE game_1.modifiers OWNER TO postgres;

--
-- TOC entry 251 (class 1259 OID 96172)
-- Name: modifiers_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

CREATE SEQUENCE game_1.modifiers_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE game_1.modifiers_id_seq OWNER TO postgres;

--
-- TOC entry 5426 (class 0 OID 0)
-- Dependencies: 251
-- Name: modifiers_id_seq; Type: SEQUENCE OWNED BY; Schema: game_1; Owner: postgres
--

ALTER SEQUENCE game_1.modifiers_id_seq OWNED BY game_1.modifiers.id;


--
-- TOC entry 252 (class 1259 OID 96173)
-- Name: nations; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1.nations (
    id integer NOT NULL,
    name text NOT NULL,
    fk_religions integer NOT NULL,
    fk_cultures integer NOT NULL,
    flag text,
    color text
);


ALTER TABLE game_1.nations OWNER TO postgres;

--
-- TOC entry 253 (class 1259 OID 96178)
-- Name: nations_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1.nations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.nations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 254 (class 1259 OID 96179)
-- Name: offeredresources; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1.offeredresources (
    id integer NOT NULL,
    fk_resource integer NOT NULL,
    fk_tradeagreement integer NOT NULL,
    quantity integer NOT NULL
);


ALTER TABLE game_1.offeredresources OWNER TO postgres;

--
-- TOC entry 255 (class 1259 OID 96182)
-- Name: offeredresources_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1.offeredresources ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.offeredresources_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 256 (class 1259 OID 96183)
-- Name: ownedResources; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1."ownedResources" (
    id integer NOT NULL,
    fk_nation integer NOT NULL,
    fk_resource integer NOT NULL,
    amount real DEFAULT 0 NOT NULL
);


ALTER TABLE game_1."ownedResources" OWNER TO postgres;

--
-- TOC entry 257 (class 1259 OID 96187)
-- Name: ownedResources_Id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

CREATE SEQUENCE game_1."ownedResources_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE game_1."ownedResources_Id_seq" OWNER TO postgres;

--
-- TOC entry 5427 (class 0 OID 0)
-- Dependencies: 257
-- Name: ownedResources_Id_seq; Type: SEQUENCE OWNED BY; Schema: game_1; Owner: postgres
--

ALTER SEQUENCE game_1."ownedResources_Id_seq" OWNED BY game_1."ownedResources".id;


--
-- TOC entry 258 (class 1259 OID 96188)
-- Name: players; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1.players (
    id integer NOT NULL,
    "fk_User" integer NOT NULL,
    "playerType" integer NOT NULL,
    name text NOT NULL
);


ALTER TABLE game_1.players OWNER TO postgres;

--
-- TOC entry 259 (class 1259 OID 96193)
-- Name: players_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1.players ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.players_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 260 (class 1259 OID 96194)
-- Name: populationproductionshares; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1.populationproductionshares (
    id integer NOT NULL,
    fk_population integer NOT NULL,
    fk_resources integer NOT NULL,
    coefficient double precision NOT NULL
);


ALTER TABLE game_1.populationproductionshares OWNER TO postgres;

--
-- TOC entry 261 (class 1259 OID 96197)
-- Name: populationproductionshares_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1.populationproductionshares ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME game_1.populationproductionshares_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 262 (class 1259 OID 96198)
-- Name: populations; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1.populations (
    id integer NOT NULL,
    fk_religions integer NOT NULL,
    fk_cultures integer NOT NULL,
    fk_socialgroups integer NOT NULL,
    fk_localisations integer NOT NULL,
    happiness real NOT NULL,
    volunteers integer
);


ALTER TABLE game_1.populations OWNER TO postgres;

--
-- TOC entry 263 (class 1259 OID 96201)
-- Name: populations_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1.populations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.populations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 264 (class 1259 OID 96202)
-- Name: populationusedresource; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1.populationusedresource (
    id integer NOT NULL,
    fk_population integer NOT NULL,
    fk_resources integer NOT NULL,
    amount double precision NOT NULL
);


ALTER TABLE game_1.populationusedresource OWNER TO postgres;

--
-- TOC entry 265 (class 1259 OID 96205)
-- Name: populationusedresource_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1.populationusedresource ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME game_1.populationusedresource_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 266 (class 1259 OID 96206)
-- Name: productionCost; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1."productionCost" (
    id integer NOT NULL,
    "fk_UnitTypes" integer NOT NULL,
    "fk_Resources" integer NOT NULL,
    amount double precision NOT NULL
);


ALTER TABLE game_1."productionCost" OWNER TO postgres;

--
-- TOC entry 267 (class 1259 OID 96209)
-- Name: productionCost_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1."productionCost" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1."productionCost_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 268 (class 1259 OID 96210)
-- Name: productionShares; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1."productionShares" (
    id integer NOT NULL,
    "fk_SocialGroups" integer NOT NULL,
    "fk_Resources" integer NOT NULL,
    coefficient double precision NOT NULL
);


ALTER TABLE game_1."productionShares" OWNER TO postgres;

--
-- TOC entry 269 (class 1259 OID 96213)
-- Name: productionShares_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1."productionShares" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1."productionShares_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 270 (class 1259 OID 96214)
-- Name: relatedEvents; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1."relatedEvents" (
    id integer NOT NULL,
    "fk_Events" integer NOT NULL,
    "fk_Nations" integer NOT NULL
);


ALTER TABLE game_1."relatedEvents" OWNER TO postgres;

--
-- TOC entry 271 (class 1259 OID 96217)
-- Name: relatedEvents_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1."relatedEvents" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1."relatedEvents_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 272 (class 1259 OID 96218)
-- Name: religions; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1.religions (
    id integer NOT NULL,
    name text NOT NULL,
    icon text
);


ALTER TABLE game_1.religions OWNER TO postgres;

--
-- TOC entry 273 (class 1259 OID 96223)
-- Name: religions_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1.religions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.religions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 274 (class 1259 OID 96224)
-- Name: resources; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1.resources (
    id integer NOT NULL,
    name text NOT NULL,
    ismain boolean NOT NULL,
    icon text,
    "constProduction" boolean DEFAULT false NOT NULL
);


ALTER TABLE game_1.resources OWNER TO postgres;

--
-- TOC entry 275 (class 1259 OID 96229)
-- Name: resources_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1.resources ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.resources_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 276 (class 1259 OID 96230)
-- Name: socialgroups; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1.socialgroups (
    id integer NOT NULL,
    name text NOT NULL,
    basehappiness real NOT NULL,
    volunteers integer NOT NULL,
    icon text
);


ALTER TABLE game_1.socialgroups OWNER TO postgres;

--
-- TOC entry 277 (class 1259 OID 96235)
-- Name: socialgroups_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1.socialgroups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.socialgroups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 278 (class 1259 OID 96236)
-- Name: tradeagreements; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1.tradeagreements (
    id integer NOT NULL,
    fk_nationoffering integer NOT NULL,
    fk_nationreceiving integer NOT NULL,
    status integer NOT NULL,
    duration integer NOT NULL,
    description text NOT NULL
);


ALTER TABLE game_1.tradeagreements OWNER TO postgres;

--
-- TOC entry 279 (class 1259 OID 96241)
-- Name: tradeagreements_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1.tradeagreements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.tradeagreements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 280 (class 1259 OID 96242)
-- Name: troops; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1.troops (
    id integer NOT NULL,
    "fk_UnitTypes" integer NOT NULL,
    "fk_Armies" integer NOT NULL,
    quantity integer NOT NULL
);


ALTER TABLE game_1.troops OWNER TO postgres;

--
-- TOC entry 281 (class 1259 OID 96245)
-- Name: troops_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1.troops ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.troops_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 282 (class 1259 OID 96246)
-- Name: unitOrders; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1."unitOrders" (
    id integer NOT NULL,
    "fk_UnitTypes" integer NOT NULL,
    "fk_Nations" integer NOT NULL,
    quantity integer NOT NULL
);


ALTER TABLE game_1."unitOrders" OWNER TO postgres;

--
-- TOC entry 283 (class 1259 OID 96249)
-- Name: unitOrders_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1."unitOrders" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1."unitOrders_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 284 (class 1259 OID 96250)
-- Name: unitTypes; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1."unitTypes" (
    id integer NOT NULL,
    name text NOT NULL,
    description text NOT NULL,
    melee integer NOT NULL,
    range integer NOT NULL,
    defense integer NOT NULL,
    speed integer NOT NULL,
    morale integer NOT NULL,
    "volunteersNeeded" integer NOT NULL,
    "isNaval" boolean NOT NULL
);


ALTER TABLE game_1."unitTypes" OWNER TO postgres;

--
-- TOC entry 285 (class 1259 OID 96255)
-- Name: unitTypes_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1."unitTypes" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1."unitTypes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 286 (class 1259 OID 96256)
-- Name: usedResources; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1."usedResources" (
    id integer NOT NULL,
    "fk_SocialGroups" integer NOT NULL,
    "fk_Resources" integer NOT NULL,
    amount double precision NOT NULL
);


ALTER TABLE game_1."usedResources" OWNER TO postgres;

--
-- TOC entry 287 (class 1259 OID 96259)
-- Name: usedResources_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1."usedResources" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1."usedResources_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 288 (class 1259 OID 96260)
-- Name: wantedresources; Type: TABLE; Schema: game_1; Owner: postgres
--

CREATE TABLE game_1.wantedresources (
    id integer NOT NULL,
    fk_resource integer NOT NULL,
    fk_tradeagreement integer NOT NULL,
    amount double precision NOT NULL
);


ALTER TABLE game_1.wantedresources OWNER TO postgres;

--
-- TOC entry 289 (class 1259 OID 96263)
-- Name: wantedresources_id_seq; Type: SEQUENCE; Schema: game_1; Owner: postgres
--

ALTER TABLE game_1.wantedresources ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_1.wantedresources_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5028 (class 2604 OID 96264)
-- Name: modifiers id; Type: DEFAULT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.modifiers ALTER COLUMN id SET DEFAULT nextval('game_1.modifiers_id_seq'::regclass);


--
-- TOC entry 5029 (class 2604 OID 96265)
-- Name: ownedResources id; Type: DEFAULT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1."ownedResources" ALTER COLUMN id SET DEFAULT nextval('game_1."ownedResources_Id_seq"'::regclass);


--
-- TOC entry 5349 (class 0 OID 96082)
-- Dependencies: 220
-- Data for Name: gameaccess; Type: TABLE DATA; Schema: Global; Owner: postgres
--

COPY "Global".gameaccess (id, "fk_Users", "fk_Games", "accessType", "isArchived", "nationName") FROM stdin;
1	1	1	1	f	\N
2	2	1	0	f	\N
3	3	1	1	f	\N
4	4	1	1	f	\N
\.


--
-- TOC entry 5351 (class 0 OID 96086)
-- Dependencies: 222
-- Data for Name: games; Type: TABLE DATA; Schema: Global; Owner: postgres
--

COPY "Global".games (id, name, description, image, "ownerId", game_code) FROM stdin;
1	default_schema	Demo testowe\r\n	\N	2	XIWDFW
2	Tesfs	TEst	\N	5	JLI1OA
\.


--
-- TOC entry 5353 (class 0 OID 96093)
-- Dependencies: 224
-- Data for Name: refresh_tokens; Type: TABLE DATA; Schema: Global; Owner: postgres
--

COPY "Global".refresh_tokens (id, user_id, token, expires_at, revoked_at, created_at) FROM stdin;
0a546c55-37d3-4698-8b15-3e77ae1d47c9	1	ZoHowE/spkY/fjWQznZA9rWuprh+5R/6RTuK37c1tkIMxqfMPeGDFkh3F3t4jyyDWMHMM2ntYxmBPlFicRkRVQ==	2026-02-22 13:08:57.823879+01	\N	2026-02-15 13:08:57.823844+01
7f20a253-bea2-4756-a7eb-4f79e599d7ca	2	AmClTQJYVm0o4bjvaXwb+Q+nXwse+06WABSm9oGinxXlKr07VmWkxgpcu/V/W3jAHOh4GBSYP+11OQwYSpYbqg==	2026-02-22 16:49:52.361271+01	\N	2026-02-15 16:49:52.361271+01
\.


--
-- TOC entry 5354 (class 0 OID 96100)
-- Dependencies: 225
-- Data for Name: users; Type: TABLE DATA; Schema: Global; Owner: postgres
--

COPY "Global".users (id, name, email, password, issso, isarchived, image) FROM stdin;
1	Test	test@test	$2a$11$s/J0zefb5amFzjdjllmuZ.AXuziyjVRcYTeEhxyemaxsJJyKnzxU2	f	f	\N
2	admin	admin@admin	$2a$11$t8DGLO5spPxXzpyRb5j0vuuk54ycsFEo9scO7xswpGCH9WvMcwive	f	f	\N
3	tomek	tomek@tomek	$2a$11$t8DGLO5spPxXzpyRb5j0vuuk54ycsFEo9scO7xswpGCH9WvMcwive	f	f	\N
4	jakub	jakub@jakub	$2a$11$t8DGLO5spPxXzpyRb5j0vuuk54ycsFEo9scO7xswpGCH9WvMcwive	f	f	\N
5	Teste	272731@student.pwr.edu.pl	$2a$11$4QPd9xbLTZr4uq8GZ2tH3.6ij.AWGiJApJZAkCQPmBHZdPWq1Wd8G	t	f	\N
\.


--
-- TOC entry 5356 (class 0 OID 96106)
-- Dependencies: 227
-- Data for Name: accessToUnits; Type: TABLE DATA; Schema: game_1; Owner: postgres
--

COPY game_1."accessToUnits" (id, "fk_Nation", "fk_UnitTypes") FROM stdin;
1	1	1
2	1	2
3	1	3
4	2	1
5	2	3
6	2	4
7	3	1
8	3	5
9	4	1
10	4	2
11	5	1
12	5	3
\.


--
-- TOC entry 5358 (class 0 OID 96110)
-- Dependencies: 229
-- Data for Name: accessestonations; Type: TABLE DATA; Schema: game_1; Owner: postgres
--

COPY game_1.accessestonations (id, fk_nations, fk_users, dateacquired, isactive) FROM stdin;
1	1	1	2025-01-01 00:00:00+01	t
2	2	2	2025-01-02 00:00:00+01	t
\.


--
-- TOC entry 5360 (class 0 OID 96114)
-- Dependencies: 231
-- Data for Name: actions; Type: TABLE DATA; Schema: game_1; Owner: postgres
--

COPY game_1.actions (id, "fk_Nations", name, description, result, "isSettled") FROM stdin;
1	1	Ekspedycja	Wysłanie ekspedycji na niezbadane tereny	\N	f
2	2	Budowa Świątyni	Rozpoczęcie budowy wielkiej świątyni	\N	f
3	3	Szlak Handlowy	Otwarcie nowego szlaku handlowego	Zwiększenie przychodów o 10%	t
4	4	Reformy	Wprowadzenie reform społecznych	\N	f
5	5	Mobilizacja	Mobilizacja sił zbrojnych	Wzrost liczebności armii o 20%	t
\.


--
-- TOC entry 5362 (class 0 OID 96120)
-- Dependencies: 233
-- Data for Name: armies; Type: TABLE DATA; Schema: game_1; Owner: postgres
--

COPY game_1.armies (id, name, "fk_Nations", fk_localisations, is_naval) FROM stdin;
1	Armia Północy	1	1	f
2	Legiony Cesarskie	2	2	f
3	Flota Republiki	3	3	t
4	Drużyna Księcia	4	4	f
5	Jeźdźcy Pustyni	5	5	f
6	Baraki	1	\N	f
7	Baraki	2	\N	f
8	Baraki	3	\N	f
9	Baraki	4	\N	f
10	Baraki	5	\N	f
11	Doki	1	\N	t
12	Doki	2	\N	t
13	Doki	3	\N	t
14	Doki	4	\N	t
15	Doki	5	\N	t
\.


--
-- TOC entry 5419 (class 0 OID 96636)
-- Dependencies: 290
-- Data for Name: armySettings; Type: TABLE DATA; Schema: game_1; Owner: postgres
--

COPY game_1."armySettings" (id, "nameOfSettingsSet", "useMeleeAtack", "useRangeAtack", "useDefense", "useSpeed", "useMorale", "useMaintanace") FROM stdin;
1	Default	t	t	t	t	t	t
\.


--
-- TOC entry 5364 (class 0 OID 96126)
-- Dependencies: 235
-- Data for Name: cultures; Type: TABLE DATA; Schema: game_1; Owner: postgres
--

COPY game_1.cultures (id, name) FROM stdin;
1	Nordycka
2	Słowiańska
3	Germańska
4	Romańska
5	Grecka
\.


--
-- TOC entry 5366 (class 0 OID 96132)
-- Dependencies: 237
-- Data for Name: events; Type: TABLE DATA; Schema: game_1; Owner: postgres
--

COPY game_1.events (id, name, description, isactive, picture) FROM stdin;
1	Wielka Bitwa	Epiczna bitwa, która zmieniła losy świata	t	battle.jpg
2	Plaga	Śmiertelna zaraza dziesiątkująca populację	t	plague.jpg
3	Odkrycie	Odkrycie nowych terenów i technologii	t	discovery.jpg
4	Rewolta	Rewolta społeczeństwa przeciwko władcy	t	revolt.jpg
5	Sojusz	Zawarcie sojuszu między narodami	t	alliance.jpg
\.


--
-- TOC entry 5368 (class 0 OID 96138)
-- Dependencies: 239
-- Data for Name: factions; Type: TABLE DATA; Schema: game_1; Owner: postgres
--

COPY game_1.factions (id, name, "fk_Nations", power, agenda, contentment, color, description) FROM stdin;
1	Konserwatyści	1	70	Utrzymanie tradycji	60	#0000FF	\N
2	Reformatorzy	1	30	Wprowadzenie zmian	40	#00FF00	\N
3	Militaryści	2	60	Ekspansja militarna	50	#FF0000	\N
4	Handlarze	2	40	Rozwój handlu	70	#FFFF00	\N
5	Zjednoczeni	3	90	Jedność narodu	80	#800080	\N
\.


--
-- TOC entry 5370 (class 0 OID 96144)
-- Dependencies: 241
-- Data for Name: localisations; Type: TABLE DATA; Schema: game_1; Owner: postgres
--

COPY game_1.localisations (id, name, size, fortifications, fk_nations) FROM stdin;
1	Stolica Północy	5	4	1
2	Twierdza Cesarska	6	5	2
3	Port Republiki	4	3	3
4	Wschodni Gród	3	2	4
5	Oaza Południowa	4	3	5
6	Górska Osada	2	1	1
7	Cesarskie Tereny	3	2	2
8	Nadmorska Wioska	2	1	3
\.


--
-- TOC entry 5371 (class 0 OID 96149)
-- Dependencies: 242
-- Data for Name: localisationsResources; Type: TABLE DATA; Schema: game_1; Owner: postgres
--

COPY game_1."localisationsResources" (id, fk_localisations, "fk_Resources", amount) FROM stdin;
1	1	1	1000
2	1	3	2000
3	2	2	1500
4	2	5	3000
5	3	1	800
6	3	8	500
7	4	3	2500
8	4	4	3500
9	5	7	600
10	5	6	400
\.


--
-- TOC entry 5374 (class 0 OID 96154)
-- Dependencies: 245
-- Data for Name: maintenanceCosts; Type: TABLE DATA; Schema: game_1; Owner: postgres
--

COPY game_1."maintenanceCosts" (id, "fk_UnitTypes", "fk_Resources", amount) FROM stdin;
1	1	1	0.5
2	1	4	1
3	2	1	0.3
4	2	3	0.5
5	3	1	1
6	3	4	1.5
7	4	1	2
8	4	3	1
9	5	1	3
10	5	3	2
\.


--
-- TOC entry 5376 (class 0 OID 96158)
-- Dependencies: 247
-- Data for Name: map; Type: TABLE DATA; Schema: game_1; Owner: postgres
--

COPY game_1.map (id, name, "mapLocation", "mapIconLocation") FROM stdin;
1	Europa Środkowa	maps/central_europe.jpg	maps/central_europe.jpg
2	Wyspy Brytyjskie	maps/british_isles.jpg	maps/central_europe.jpg
3	Półwysep Iberyjski	maps/iberia.jpg	maps/central_europe.jpg
4	Skandynawia	maps/scandinavia.jpg	maps/central_europe.jpg
5	Bałkany	maps/balkans.jpg	maps/central_europe.jpg
\.


--
-- TOC entry 5377 (class 0 OID 96163)
-- Dependencies: 248
-- Data for Name: mapAccess; Type: TABLE DATA; Schema: game_1; Owner: postgres
--

COPY game_1."mapAccess" ("fk_Nations", "fk_Maps") FROM stdin;
1	1
1	4
2	2
2	5
3	3
4	1
4	5
\.


--
-- TOC entry 5379 (class 0 OID 96167)
-- Dependencies: 250
-- Data for Name: modifiers; Type: TABLE DATA; Schema: game_1; Owner: postgres
--

COPY game_1.modifiers (id, event_id, modifier_type, effects) FROM stdin;
\.


--
-- TOC entry 5381 (class 0 OID 96173)
-- Dependencies: 252
-- Data for Name: nations; Type: TABLE DATA; Schema: game_1; Owner: postgres
--

COPY game_1.nations (id, name, fk_religions, fk_cultures, flag, color) FROM stdin;
1	Królestwo Północy	1	1	\N	red
2	Cesarstwo Centralne	2	3	\N	yellow
3	Republika Nadmorska	2	4	\N	red
4	Księstwo Wschodnie	1	2	\N	green
5	Kalifat Południowy	3	5	\N	blue
\.


--
-- TOC entry 5383 (class 0 OID 96179)
-- Dependencies: 254
-- Data for Name: offeredresources; Type: TABLE DATA; Schema: game_1; Owner: postgres
--

COPY game_1.offeredresources (id, fk_resource, fk_tradeagreement, quantity) FROM stdin;
1	2	1	100
2	3	1	200
3	1	3	50
4	4	3	300
5	3	4	150
\.


--
-- TOC entry 5385 (class 0 OID 96183)
-- Dependencies: 256
-- Data for Name: ownedResources; Type: TABLE DATA; Schema: game_1; Owner: postgres
--

COPY game_1."ownedResources" (id, fk_nation, fk_resource, amount) FROM stdin;
1	1	1	4201
2	1	2	4202
3	1	3	4203
4	1	4	4204
5	1	5	4205
6	1	6	4206
7	1	7	4207
8	1	8	4208
9	1	9	4209
10	2	1	2137
11	2	2	2173
12	2	3	1237
13	2	4	2137
14	2	5	1273
15	2	6	2137
16	2	7	1237
17	2	8	2173
18	2	9	1237
19	3	1	4201
20	3	2	4202
21	3	3	4203
22	3	4	4204
23	3	5	4205
24	3	6	4206
25	3	7	4207
26	3	8	4208
27	3	9	4209
28	4	1	2137
29	4	2	2173
30	4	3	1237
31	4	4	2137
32	4	5	1273
33	4	6	2137
34	4	7	1237
35	4	8	2173
36	4	9	1237
37	5	1	2137
38	5	2	2173
39	5	3	1237
40	5	4	2137
41	5	5	1273
42	5	6	2137
43	5	7	1237
44	5	8	2173
45	5	9	1237
\.


--
-- TOC entry 5387 (class 0 OID 96188)
-- Dependencies: 258
-- Data for Name: players; Type: TABLE DATA; Schema: game_1; Owner: postgres
--

COPY game_1.players (id, "fk_User", "playerType", name) FROM stdin;
1	1	1	Test
2	2	0	admin
3	3	1	tomek
4	4	1	jakub
\.


--
-- TOC entry 5389 (class 0 OID 96194)
-- Dependencies: 260
-- Data for Name: populationproductionshares; Type: TABLE DATA; Schema: game_1; Owner: postgres
--

COPY game_1.populationproductionshares (id, fk_population, fk_resources, coefficient) FROM stdin;
1	1	1	1.1
2	1	2	2.1
3	2	1	3.7
4	3	3	6.9
5	4	4	1.2
6	5	5	1.2
7	6	6	0.9
8	7	7	1.3
9	7	1	1
10	7	7	0.5
\.


--
-- TOC entry 5391 (class 0 OID 96198)
-- Dependencies: 262
-- Data for Name: populations; Type: TABLE DATA; Schema: game_1; Owner: postgres
--

COPY game_1.populations (id, fk_religions, fk_cultures, fk_socialgroups, fk_localisations, happiness, volunteers) FROM stdin;
1	1	1	1	1	5.5	3
2	2	3	2	2	6	3
3	2	4	3	3	7.2	1
4	1	2	1	4	4.8	2
5	3	5	5	5	5.7	2
6	1	1	2	6	5.2	1
7	2	3	4	7	6.8	1
8	2	4	5	8	6.3	1
\.


--
-- TOC entry 5393 (class 0 OID 96202)
-- Dependencies: 264
-- Data for Name: populationusedresource; Type: TABLE DATA; Schema: game_1; Owner: postgres
--

COPY game_1.populationusedresource (id, fk_population, fk_resources, amount) FROM stdin;
1	1	1	0.1
2	1	2	1.1
3	1	3	2.7
4	3	3	0.9
5	4	4	1.2
6	5	5	1.4
7	6	6	0.7
8	7	7	1.3
9	7	4	30
\.


--
-- TOC entry 5395 (class 0 OID 96206)
-- Dependencies: 266
-- Data for Name: productionCost; Type: TABLE DATA; Schema: game_1; Owner: postgres
--

COPY game_1."productionCost" (id, "fk_UnitTypes", "fk_Resources", amount) FROM stdin;
1	1	1	10
2	1	2	5
3	2	1	8
4	2	3	10
5	3	1	20
6	3	2	15
7	4	1	30
8	4	3	25
9	5	1	50
10	5	2	30
\.


--
-- TOC entry 5397 (class 0 OID 96210)
-- Dependencies: 268
-- Data for Name: productionShares; Type: TABLE DATA; Schema: game_1; Owner: postgres
--

COPY game_1."productionShares" (id, "fk_SocialGroups", "fk_Resources", coefficient) FROM stdin;
1	1	3	2
2	1	4	3
3	2	1	1.5
4	2	6	2
5	3	2	1
6	3	5	1.5
9	5	1	2.5
10	5	8	2
11	4	1	1
12	4	7	0.5
\.


--
-- TOC entry 5399 (class 0 OID 96214)
-- Dependencies: 270
-- Data for Name: relatedEvents; Type: TABLE DATA; Schema: game_1; Owner: postgres
--

COPY game_1."relatedEvents" (id, "fk_Events", "fk_Nations") FROM stdin;
1	1	1
2	1	2
3	2	3
4	2	4
5	3	1
6	3	5
7	4	2
8	4	4
9	5	1
10	5	3
\.


--
-- TOC entry 5401 (class 0 OID 96218)
-- Dependencies: 272
-- Data for Name: religions; Type: TABLE DATA; Schema: game_1; Owner: postgres
--

COPY game_1.religions (id, name, icon) FROM stdin;
1	Pogaństwo	\N
2	Chrześcijaństwo	\N
3	Islam	\N
4	Judaizm	\N
5	Zoroastrianizm	\N
\.


--
-- TOC entry 5403 (class 0 OID 96224)
-- Dependencies: 274
-- Data for Name: resources; Type: TABLE DATA; Schema: game_1; Owner: postgres
--

COPY game_1.resources (id, name, ismain, icon, "constProduction") FROM stdin;
1	Złoto	t	\N	f
2	Żelazo	t	\N	f
3	Drewno	t	\N	f
4	Żywność	t	\N	f
5	Kamień	t	\N	f
6	Tkaniny	f	\N	f
7	Przyprawy	f	\N	f
8	Wino	f	\N	f
9	Drewno	t	\N	f
11	Miód	t	\N	f
\.


--
-- TOC entry 5405 (class 0 OID 96230)
-- Dependencies: 276
-- Data for Name: socialgroups; Type: TABLE DATA; Schema: game_1; Owner: postgres
--

COPY game_1.socialgroups (id, name, basehappiness, volunteers, icon) FROM stdin;
1	Chłopi	5	10	\N
2	Mieszczanie	6	20	\N
3	Szlachta	7	30	\N
5	Kupcy	6.5	15	\N
4	Duchowieństwo	8	5	\N
\.


--
-- TOC entry 5407 (class 0 OID 96236)
-- Dependencies: 278
-- Data for Name: tradeagreements; Type: TABLE DATA; Schema: game_1; Owner: postgres
--

COPY game_1.tradeagreements (id, fk_nationoffering, fk_nationreceiving, status, duration, description) FROM stdin;
1	1	2	0	10	I am description
2	1	3	0	5	I am also description
3	2	4	3	8	But I m not description
4	3	5	1	12	What about me?
5	4	5	2	6	
\.


--
-- TOC entry 5409 (class 0 OID 96242)
-- Dependencies: 280
-- Data for Name: troops; Type: TABLE DATA; Schema: game_1; Owner: postgres
--

COPY game_1.troops (id, "fk_UnitTypes", "fk_Armies", quantity) FROM stdin;
1	1	1	500
2	2	1	300
3	3	2	400
4	1	2	600
5	5	3	20
6	1	4	300
7	3	4	150
10	3	5	4
15	3	10	120
18	3	10	120
\.


--
-- TOC entry 5411 (class 0 OID 96246)
-- Dependencies: 282
-- Data for Name: unitOrders; Type: TABLE DATA; Schema: game_1; Owner: postgres
--

COPY game_1."unitOrders" (id, "fk_UnitTypes", "fk_Nations", quantity) FROM stdin;
1	1	1	1
2	1	2	1
3	3	2	3
4	4	2	1
5	1	3	8
6	5	3	5
7	1	4	2
8	2	4	4
9	1	5	1
10	3	5	4
12	2	1	1
\.


--
-- TOC entry 5413 (class 0 OID 96250)
-- Dependencies: 284
-- Data for Name: unitTypes; Type: TABLE DATA; Schema: game_1; Owner: postgres
--

COPY game_1."unitTypes" (id, name, description, melee, range, defense, speed, morale, "volunteersNeeded", "isNaval") FROM stdin;
1	Piechota	Podstawowa jednostka piechoty	5	0	3	3	5	100	f
2	Łucznicy	Jednostka łuczników	1	6	2	3	4	80	f
3	Kawaleria	Szybka jednostka kawalerii	7	0	4	6	7	120	f
4	Oblężnicza	Machiny oblężnicze	1	8	1	2	3	150	f
5	Okręty wojenne	Okręty bojowe	6	4	5	4	6	200	t
\.


--
-- TOC entry 5415 (class 0 OID 96256)
-- Dependencies: 286
-- Data for Name: usedResources; Type: TABLE DATA; Schema: game_1; Owner: postgres
--

COPY game_1."usedResources" (id, "fk_SocialGroups", "fk_Resources", amount) FROM stdin;
1	1	4	100
2	1	3	50
3	2	4	75
4	2	6	25
5	3	4	50
6	3	8	30
9	5	4	60
10	5	6	40
11	4	4	30
\.


--
-- TOC entry 5417 (class 0 OID 96260)
-- Dependencies: 288
-- Data for Name: wantedresources; Type: TABLE DATA; Schema: game_1; Owner: postgres
--

COPY game_1.wantedresources (id, fk_resource, fk_tradeagreement, amount) FROM stdin;
1	1	1	50
2	4	1	100
3	2	3	75
4	5	3	200
5	7	4	25
\.


--
-- TOC entry 5428 (class 0 OID 0)
-- Dependencies: 221
-- Name: gameaccess_id_seq; Type: SEQUENCE SET; Schema: Global; Owner: postgres
--

SELECT pg_catalog.setval('"Global".gameaccess_id_seq', 4, true);


--
-- TOC entry 5429 (class 0 OID 0)
-- Dependencies: 223
-- Name: games_id_seq; Type: SEQUENCE SET; Schema: Global; Owner: postgres
--

SELECT pg_catalog.setval('"Global".games_id_seq', 2, true);


--
-- TOC entry 5430 (class 0 OID 0)
-- Dependencies: 226
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: Global; Owner: postgres
--

SELECT pg_catalog.setval('"Global".users_id_seq', 5, true);


--
-- TOC entry 5431 (class 0 OID 0)
-- Dependencies: 228
-- Name: accessToUnits_id_seq; Type: SEQUENCE SET; Schema: game_1; Owner: postgres
--

SELECT pg_catalog.setval('game_1."accessToUnits_id_seq"', 12, true);


--
-- TOC entry 5432 (class 0 OID 0)
-- Dependencies: 230
-- Name: accessestonations_id_seq; Type: SEQUENCE SET; Schema: game_1; Owner: postgres
--

SELECT pg_catalog.setval('game_1.accessestonations_id_seq', 5, true);


--
-- TOC entry 5433 (class 0 OID 0)
-- Dependencies: 232
-- Name: actions_id_seq; Type: SEQUENCE SET; Schema: game_1; Owner: postgres
--

SELECT pg_catalog.setval('game_1.actions_id_seq', 5, true);


--
-- TOC entry 5434 (class 0 OID 0)
-- Dependencies: 234
-- Name: armies_id_seq; Type: SEQUENCE SET; Schema: game_1; Owner: postgres
--

SELECT pg_catalog.setval('game_1.armies_id_seq', 15, true);


--
-- TOC entry 5435 (class 0 OID 0)
-- Dependencies: 291
-- Name: army_settings_id_seq; Type: SEQUENCE SET; Schema: game_1; Owner: postgres
--

SELECT pg_catalog.setval('game_1.army_settings_id_seq', 1, true);


--
-- TOC entry 5436 (class 0 OID 0)
-- Dependencies: 236
-- Name: cultures_id_seq; Type: SEQUENCE SET; Schema: game_1; Owner: postgres
--

SELECT pg_catalog.setval('game_1.cultures_id_seq', 5, true);


--
-- TOC entry 5437 (class 0 OID 0)
-- Dependencies: 238
-- Name: events_id_seq; Type: SEQUENCE SET; Schema: game_1; Owner: postgres
--

SELECT pg_catalog.setval('game_1.events_id_seq', 5, true);


--
-- TOC entry 5438 (class 0 OID 0)
-- Dependencies: 240
-- Name: factions_id_seq; Type: SEQUENCE SET; Schema: game_1; Owner: postgres
--

SELECT pg_catalog.setval('game_1.factions_id_seq', 5, true);


--
-- TOC entry 5439 (class 0 OID 0)
-- Dependencies: 243
-- Name: localisationsResources_id_seq; Type: SEQUENCE SET; Schema: game_1; Owner: postgres
--

SELECT pg_catalog.setval('game_1."localisationsResources_id_seq"', 10, true);


--
-- TOC entry 5440 (class 0 OID 0)
-- Dependencies: 244
-- Name: localisations_id_seq; Type: SEQUENCE SET; Schema: game_1; Owner: postgres
--

SELECT pg_catalog.setval('game_1.localisations_id_seq', 8, true);


--
-- TOC entry 5441 (class 0 OID 0)
-- Dependencies: 246
-- Name: maintenanceCosts_id_seq; Type: SEQUENCE SET; Schema: game_1; Owner: postgres
--

SELECT pg_catalog.setval('game_1."maintenanceCosts_id_seq"', 10, true);


--
-- TOC entry 5442 (class 0 OID 0)
-- Dependencies: 249
-- Name: map_id_seq; Type: SEQUENCE SET; Schema: game_1; Owner: postgres
--

SELECT pg_catalog.setval('game_1.map_id_seq', 5, true);


--
-- TOC entry 5443 (class 0 OID 0)
-- Dependencies: 251
-- Name: modifiers_id_seq; Type: SEQUENCE SET; Schema: game_1; Owner: postgres
--

SELECT pg_catalog.setval('game_1.modifiers_id_seq', 1, false);


--
-- TOC entry 5444 (class 0 OID 0)
-- Dependencies: 253
-- Name: nations_id_seq; Type: SEQUENCE SET; Schema: game_1; Owner: postgres
--

SELECT pg_catalog.setval('game_1.nations_id_seq', 5, true);


--
-- TOC entry 5445 (class 0 OID 0)
-- Dependencies: 255
-- Name: offeredresources_id_seq; Type: SEQUENCE SET; Schema: game_1; Owner: postgres
--

SELECT pg_catalog.setval('game_1.offeredresources_id_seq', 5, true);


--
-- TOC entry 5446 (class 0 OID 0)
-- Dependencies: 257
-- Name: ownedResources_Id_seq; Type: SEQUENCE SET; Schema: game_1; Owner: postgres
--

SELECT pg_catalog.setval('game_1."ownedResources_Id_seq"', 45, true);


--
-- TOC entry 5447 (class 0 OID 0)
-- Dependencies: 259
-- Name: players_id_seq; Type: SEQUENCE SET; Schema: game_1; Owner: postgres
--

SELECT pg_catalog.setval('game_1.players_id_seq', 4, true);


--
-- TOC entry 5448 (class 0 OID 0)
-- Dependencies: 261
-- Name: populationproductionshares_id_seq; Type: SEQUENCE SET; Schema: game_1; Owner: postgres
--

SELECT pg_catalog.setval('game_1.populationproductionshares_id_seq', 10, true);


--
-- TOC entry 5449 (class 0 OID 0)
-- Dependencies: 263
-- Name: populations_id_seq; Type: SEQUENCE SET; Schema: game_1; Owner: postgres
--

SELECT pg_catalog.setval('game_1.populations_id_seq', 8, true);


--
-- TOC entry 5450 (class 0 OID 0)
-- Dependencies: 265
-- Name: populationusedresource_id_seq; Type: SEQUENCE SET; Schema: game_1; Owner: postgres
--

SELECT pg_catalog.setval('game_1.populationusedresource_id_seq', 9, true);


--
-- TOC entry 5451 (class 0 OID 0)
-- Dependencies: 267
-- Name: productionCost_id_seq; Type: SEQUENCE SET; Schema: game_1; Owner: postgres
--

SELECT pg_catalog.setval('game_1."productionCost_id_seq"', 10, true);


--
-- TOC entry 5452 (class 0 OID 0)
-- Dependencies: 269
-- Name: productionShares_id_seq; Type: SEQUENCE SET; Schema: game_1; Owner: postgres
--

SELECT pg_catalog.setval('game_1."productionShares_id_seq"', 12, true);


--
-- TOC entry 5453 (class 0 OID 0)
-- Dependencies: 271
-- Name: relatedEvents_id_seq; Type: SEQUENCE SET; Schema: game_1; Owner: postgres
--

SELECT pg_catalog.setval('game_1."relatedEvents_id_seq"', 10, true);


--
-- TOC entry 5454 (class 0 OID 0)
-- Dependencies: 273
-- Name: religions_id_seq; Type: SEQUENCE SET; Schema: game_1; Owner: postgres
--

SELECT pg_catalog.setval('game_1.religions_id_seq', 5, true);


--
-- TOC entry 5455 (class 0 OID 0)
-- Dependencies: 275
-- Name: resources_id_seq; Type: SEQUENCE SET; Schema: game_1; Owner: postgres
--

SELECT pg_catalog.setval('game_1.resources_id_seq', 11, true);


--
-- TOC entry 5456 (class 0 OID 0)
-- Dependencies: 277
-- Name: socialgroups_id_seq; Type: SEQUENCE SET; Schema: game_1; Owner: postgres
--

SELECT pg_catalog.setval('game_1.socialgroups_id_seq', 5, true);


--
-- TOC entry 5457 (class 0 OID 0)
-- Dependencies: 279
-- Name: tradeagreements_id_seq; Type: SEQUENCE SET; Schema: game_1; Owner: postgres
--

SELECT pg_catalog.setval('game_1.tradeagreements_id_seq', 5, true);


--
-- TOC entry 5458 (class 0 OID 0)
-- Dependencies: 281
-- Name: troops_id_seq; Type: SEQUENCE SET; Schema: game_1; Owner: postgres
--

SELECT pg_catalog.setval('game_1.troops_id_seq', 8, true);


--
-- TOC entry 5459 (class 0 OID 0)
-- Dependencies: 283
-- Name: unitOrders_id_seq; Type: SEQUENCE SET; Schema: game_1; Owner: postgres
--

SELECT pg_catalog.setval('game_1."unitOrders_id_seq"', 12, true);


--
-- TOC entry 5460 (class 0 OID 0)
-- Dependencies: 285
-- Name: unitTypes_id_seq; Type: SEQUENCE SET; Schema: game_1; Owner: postgres
--

SELECT pg_catalog.setval('game_1."unitTypes_id_seq"', 5, true);


--
-- TOC entry 5461 (class 0 OID 0)
-- Dependencies: 287
-- Name: usedResources_id_seq; Type: SEQUENCE SET; Schema: game_1; Owner: postgres
--

SELECT pg_catalog.setval('game_1."usedResources_id_seq"', 11, true);


--
-- TOC entry 5462 (class 0 OID 0)
-- Dependencies: 289
-- Name: wantedresources_id_seq; Type: SEQUENCE SET; Schema: game_1; Owner: postgres
--

SELECT pg_catalog.setval('game_1.wantedresources_id_seq', 5, true);


--
-- TOC entry 5040 (class 2606 OID 96267)
-- Name: gameaccess PK_gameaccess; Type: CONSTRAINT; Schema: Global; Owner: postgres
--

ALTER TABLE ONLY "Global".gameaccess
    ADD CONSTRAINT "PK_gameaccess" PRIMARY KEY ("fk_Users", "fk_Games");


--
-- TOC entry 5044 (class 2606 OID 96269)
-- Name: games PK_games; Type: CONSTRAINT; Schema: Global; Owner: postgres
--

ALTER TABLE ONLY "Global".games
    ADD CONSTRAINT "PK_games" PRIMARY KEY (id);


--
-- TOC entry 5050 (class 2606 OID 96271)
-- Name: users PK_users; Type: CONSTRAINT; Schema: Global; Owner: postgres
--

ALTER TABLE ONLY "Global".users
    ADD CONSTRAINT "PK_users" PRIMARY KEY (id);


--
-- TOC entry 5046 (class 2606 OID 96273)
-- Name: refresh_tokens refresh_tokens_pkey; Type: CONSTRAINT; Schema: Global; Owner: postgres
--

ALTER TABLE ONLY "Global".refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);


--
-- TOC entry 5054 (class 2606 OID 96275)
-- Name: accessToUnits PK_accessToUnits; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1."accessToUnits"
    ADD CONSTRAINT "PK_accessToUnits" PRIMARY KEY (id);


--
-- TOC entry 5058 (class 2606 OID 96277)
-- Name: accessestonations PK_accessestonations; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.accessestonations
    ADD CONSTRAINT "PK_accessestonations" PRIMARY KEY (id);


--
-- TOC entry 5061 (class 2606 OID 96279)
-- Name: actions PK_actions; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.actions
    ADD CONSTRAINT "PK_actions" PRIMARY KEY (id);


--
-- TOC entry 5065 (class 2606 OID 96281)
-- Name: armies PK_armies; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.armies
    ADD CONSTRAINT "PK_armies" PRIMARY KEY (id);


--
-- TOC entry 5067 (class 2606 OID 96283)
-- Name: cultures PK_cultures; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.cultures
    ADD CONSTRAINT "PK_cultures" PRIMARY KEY (id);


--
-- TOC entry 5069 (class 2606 OID 96285)
-- Name: events PK_events; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.events
    ADD CONSTRAINT "PK_events" PRIMARY KEY (id);


--
-- TOC entry 5072 (class 2606 OID 96287)
-- Name: factions PK_factions; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.factions
    ADD CONSTRAINT "PK_factions" PRIMARY KEY (id);


--
-- TOC entry 5075 (class 2606 OID 96289)
-- Name: localisations PK_localisations; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.localisations
    ADD CONSTRAINT "PK_localisations" PRIMARY KEY (id);


--
-- TOC entry 5077 (class 2606 OID 96291)
-- Name: localisationsResources PK_localisationsResources; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1."localisationsResources"
    ADD CONSTRAINT "PK_localisationsResources" PRIMARY KEY (id);


--
-- TOC entry 5081 (class 2606 OID 96293)
-- Name: maintenanceCosts PK_maintenanceCosts; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1."maintenanceCosts"
    ADD CONSTRAINT "PK_maintenanceCosts" PRIMARY KEY (id);


--
-- TOC entry 5083 (class 2606 OID 96295)
-- Name: map PK_map; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.map
    ADD CONSTRAINT "PK_map" PRIMARY KEY (id);


--
-- TOC entry 5086 (class 2606 OID 96297)
-- Name: mapAccess PK_mapAccess; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1."mapAccess"
    ADD CONSTRAINT "PK_mapAccess" PRIMARY KEY ("fk_Nations", "fk_Maps");


--
-- TOC entry 5090 (class 2606 OID 96299)
-- Name: nations PK_nations; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.nations
    ADD CONSTRAINT "PK_nations" PRIMARY KEY (id);


--
-- TOC entry 5094 (class 2606 OID 96301)
-- Name: offeredresources PK_offeredresources; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.offeredresources
    ADD CONSTRAINT "PK_offeredresources" PRIMARY KEY (id);


--
-- TOC entry 5098 (class 2606 OID 96303)
-- Name: players PK_players; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.players
    ADD CONSTRAINT "PK_players" PRIMARY KEY (id);


--
-- TOC entry 5106 (class 2606 OID 96305)
-- Name: populations PK_populations; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.populations
    ADD CONSTRAINT "PK_populations" PRIMARY KEY (id);


--
-- TOC entry 5112 (class 2606 OID 96307)
-- Name: productionCost PK_productionCost; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1."productionCost"
    ADD CONSTRAINT "PK_productionCost" PRIMARY KEY (id);


--
-- TOC entry 5114 (class 2606 OID 96309)
-- Name: productionShares PK_productionShares; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1."productionShares"
    ADD CONSTRAINT "PK_productionShares" PRIMARY KEY (id);


--
-- TOC entry 5118 (class 2606 OID 96311)
-- Name: relatedEvents PK_relatedEvents; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1."relatedEvents"
    ADD CONSTRAINT "PK_relatedEvents" PRIMARY KEY (id);


--
-- TOC entry 5120 (class 2606 OID 96313)
-- Name: religions PK_religions; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.religions
    ADD CONSTRAINT "PK_religions" PRIMARY KEY (id);


--
-- TOC entry 5122 (class 2606 OID 96315)
-- Name: resources PK_resources; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.resources
    ADD CONSTRAINT "PK_resources" PRIMARY KEY (id);


--
-- TOC entry 5124 (class 2606 OID 96317)
-- Name: socialgroups PK_socialgroups; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.socialgroups
    ADD CONSTRAINT "PK_socialgroups" PRIMARY KEY (id);


--
-- TOC entry 5128 (class 2606 OID 96319)
-- Name: tradeagreements PK_tradeagreements; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.tradeagreements
    ADD CONSTRAINT "PK_tradeagreements" PRIMARY KEY (id);


--
-- TOC entry 5132 (class 2606 OID 96321)
-- Name: troops PK_troops; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.troops
    ADD CONSTRAINT "PK_troops" PRIMARY KEY (id);


--
-- TOC entry 5136 (class 2606 OID 96323)
-- Name: unitOrders PK_unitOrders; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1."unitOrders"
    ADD CONSTRAINT "PK_unitOrders" PRIMARY KEY (id);


--
-- TOC entry 5138 (class 2606 OID 96325)
-- Name: unitTypes PK_unitTypes; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1."unitTypes"
    ADD CONSTRAINT "PK_unitTypes" PRIMARY KEY (id);


--
-- TOC entry 5140 (class 2606 OID 96327)
-- Name: usedResources PK_usedResources; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1."usedResources"
    ADD CONSTRAINT "PK_usedResources" PRIMARY KEY (id);


--
-- TOC entry 5144 (class 2606 OID 96329)
-- Name: wantedresources PK_wantedresources; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.wantedresources
    ADD CONSTRAINT "PK_wantedresources" PRIMARY KEY (id);


--
-- TOC entry 5146 (class 2606 OID 96642)
-- Name: armySettings army_settings_pkey; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1."armySettings"
    ADD CONSTRAINT army_settings_pkey PRIMARY KEY (id);


--
-- TOC entry 5088 (class 2606 OID 96331)
-- Name: modifiers modifiers_pkey; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.modifiers
    ADD CONSTRAINT modifiers_pkey PRIMARY KEY (id);


--
-- TOC entry 5096 (class 2606 OID 96333)
-- Name: ownedResources ownedResources_pkey; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1."ownedResources"
    ADD CONSTRAINT "ownedResources_pkey" PRIMARY KEY (id);


--
-- TOC entry 5100 (class 2606 OID 96335)
-- Name: populationproductionshares populationproductionshares_pkey; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.populationproductionshares
    ADD CONSTRAINT populationproductionshares_pkey PRIMARY KEY (id);


--
-- TOC entry 5108 (class 2606 OID 96337)
-- Name: populationusedresource populationusedresource_pkey; Type: CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.populationusedresource
    ADD CONSTRAINT populationusedresource_pkey PRIMARY KEY (id);


--
-- TOC entry 5038 (class 1259 OID 96338)
-- Name: IX_gameaccess_fk_Games; Type: INDEX; Schema: Global; Owner: postgres
--

CREATE INDEX "IX_gameaccess_fk_Games" ON "Global".gameaccess USING btree ("fk_Games");


--
-- TOC entry 5041 (class 1259 OID 96339)
-- Name: IX_games_name; Type: INDEX; Schema: Global; Owner: postgres
--

CREATE UNIQUE INDEX "IX_games_name" ON "Global".games USING btree (name);


--
-- TOC entry 5042 (class 1259 OID 96340)
-- Name: IX_games_ownerId; Type: INDEX; Schema: Global; Owner: postgres
--

CREATE INDEX "IX_games_ownerId" ON "Global".games USING btree ("ownerId");


--
-- TOC entry 5047 (class 1259 OID 96341)
-- Name: IX_users_email; Type: INDEX; Schema: Global; Owner: postgres
--

CREATE UNIQUE INDEX "IX_users_email" ON "Global".users USING btree (email);


--
-- TOC entry 5048 (class 1259 OID 96342)
-- Name: IX_users_name; Type: INDEX; Schema: Global; Owner: postgres
--

CREATE UNIQUE INDEX "IX_users_name" ON "Global".users USING btree (name);


--
-- TOC entry 5051 (class 1259 OID 96343)
-- Name: IX_accessToUnits_fk_Nations; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_accessToUnits_fk_Nations" ON game_1."accessToUnits" USING btree ("fk_Nation");


--
-- TOC entry 5052 (class 1259 OID 96344)
-- Name: IX_accessToUnits_fk_UnitTypes; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_accessToUnits_fk_UnitTypes" ON game_1."accessToUnits" USING btree ("fk_UnitTypes");


--
-- TOC entry 5055 (class 1259 OID 96345)
-- Name: IX_accessestonations_fk_nations; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_accessestonations_fk_nations" ON game_1.accessestonations USING btree (fk_nations);


--
-- TOC entry 5056 (class 1259 OID 96346)
-- Name: IX_accessestonations_fk_users; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_accessestonations_fk_users" ON game_1.accessestonations USING btree (fk_users);


--
-- TOC entry 5059 (class 1259 OID 96347)
-- Name: IX_actions_fk_Nations; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_actions_fk_Nations" ON game_1.actions USING btree ("fk_Nations");


--
-- TOC entry 5062 (class 1259 OID 96348)
-- Name: IX_armies_fk_Nations; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_armies_fk_Nations" ON game_1.armies USING btree ("fk_Nations");


--
-- TOC entry 5063 (class 1259 OID 96349)
-- Name: IX_armies_fk_localisations; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_armies_fk_localisations" ON game_1.armies USING btree (fk_localisations);


--
-- TOC entry 5070 (class 1259 OID 96350)
-- Name: IX_factions_fk_Nations; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_factions_fk_Nations" ON game_1.factions USING btree ("fk_Nations");


--
-- TOC entry 5073 (class 1259 OID 96351)
-- Name: IX_localisations_fk_nations; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_localisations_fk_nations" ON game_1.localisations USING btree (fk_nations);


--
-- TOC entry 5078 (class 1259 OID 96352)
-- Name: IX_maintenanceCosts_fk_Resources; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_maintenanceCosts_fk_Resources" ON game_1."maintenanceCosts" USING btree ("fk_Resources");


--
-- TOC entry 5079 (class 1259 OID 96353)
-- Name: IX_maintenanceCosts_fk_UnitTypes; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_maintenanceCosts_fk_UnitTypes" ON game_1."maintenanceCosts" USING btree ("fk_UnitTypes");


--
-- TOC entry 5084 (class 1259 OID 96354)
-- Name: IX_mapAccess_fk_Maps; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_mapAccess_fk_Maps" ON game_1."mapAccess" USING btree ("fk_Maps");


--
-- TOC entry 5091 (class 1259 OID 96355)
-- Name: IX_offeredresources_fk_resource; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_offeredresources_fk_resource" ON game_1.offeredresources USING btree (fk_resource);


--
-- TOC entry 5092 (class 1259 OID 96356)
-- Name: IX_offeredresources_fk_tradeagreement; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_offeredresources_fk_tradeagreement" ON game_1.offeredresources USING btree (fk_tradeagreement);


--
-- TOC entry 5101 (class 1259 OID 96357)
-- Name: IX_populations_fk_cultures; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_populations_fk_cultures" ON game_1.populations USING btree (fk_cultures);


--
-- TOC entry 5102 (class 1259 OID 96358)
-- Name: IX_populations_fk_localisations; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_populations_fk_localisations" ON game_1.populations USING btree (fk_localisations);


--
-- TOC entry 5103 (class 1259 OID 96359)
-- Name: IX_populations_fk_religions; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_populations_fk_religions" ON game_1.populations USING btree (fk_religions);


--
-- TOC entry 5104 (class 1259 OID 96360)
-- Name: IX_populations_fk_socialgroups; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_populations_fk_socialgroups" ON game_1.populations USING btree (fk_socialgroups);


--
-- TOC entry 5109 (class 1259 OID 96361)
-- Name: IX_productionCost_fk_Resources; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_productionCost_fk_Resources" ON game_1."productionCost" USING btree ("fk_Resources");


--
-- TOC entry 5110 (class 1259 OID 96362)
-- Name: IX_productionCost_fk_UnitTypes; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_productionCost_fk_UnitTypes" ON game_1."productionCost" USING btree ("fk_UnitTypes");


--
-- TOC entry 5115 (class 1259 OID 96363)
-- Name: IX_relatedEvents_fk_Events; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_relatedEvents_fk_Events" ON game_1."relatedEvents" USING btree ("fk_Events");


--
-- TOC entry 5116 (class 1259 OID 96364)
-- Name: IX_relatedEvents_fk_Nations; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_relatedEvents_fk_Nations" ON game_1."relatedEvents" USING btree ("fk_Nations");


--
-- TOC entry 5125 (class 1259 OID 96365)
-- Name: IX_tradeagreements_fk_nationoffering; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_tradeagreements_fk_nationoffering" ON game_1.tradeagreements USING btree (fk_nationoffering);


--
-- TOC entry 5126 (class 1259 OID 96366)
-- Name: IX_tradeagreements_fk_nationreceiving; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_tradeagreements_fk_nationreceiving" ON game_1.tradeagreements USING btree (fk_nationreceiving);


--
-- TOC entry 5129 (class 1259 OID 96367)
-- Name: IX_troops_fk_Armies; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_troops_fk_Armies" ON game_1.troops USING btree ("fk_Armies");


--
-- TOC entry 5130 (class 1259 OID 96368)
-- Name: IX_troops_fk_UnitTypes; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_troops_fk_UnitTypes" ON game_1.troops USING btree ("fk_UnitTypes");


--
-- TOC entry 5133 (class 1259 OID 96369)
-- Name: IX_unitOrders_fk_Nations; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_unitOrders_fk_Nations" ON game_1."unitOrders" USING btree ("fk_Nations");


--
-- TOC entry 5134 (class 1259 OID 96370)
-- Name: IX_unitOrders_fk_UnitTypes; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_unitOrders_fk_UnitTypes" ON game_1."unitOrders" USING btree ("fk_UnitTypes");


--
-- TOC entry 5141 (class 1259 OID 96371)
-- Name: IX_wantedresources_fk_resource; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_wantedresources_fk_resource" ON game_1.wantedresources USING btree (fk_resource);


--
-- TOC entry 5142 (class 1259 OID 96372)
-- Name: IX_wantedresources_fk_tradeagreement; Type: INDEX; Schema: game_1; Owner: postgres
--

CREATE INDEX "IX_wantedresources_fk_tradeagreement" ON game_1.wantedresources USING btree (fk_tradeagreement);


--
-- TOC entry 5198 (class 2620 OID 96373)
-- Name: nations trg_after_nations_insert; Type: TRIGGER; Schema: game_1; Owner: postgres
--

CREATE TRIGGER trg_after_nations_insert AFTER INSERT ON game_1.nations FOR EACH ROW EXECUTE FUNCTION game_1.add_nation_to_all_resources();


--
-- TOC entry 5200 (class 2620 OID 96374)
-- Name: populations trg_after_populations_insert; Type: TRIGGER; Schema: game_1; Owner: postgres
--

CREATE TRIGGER trg_after_populations_insert AFTER INSERT ON game_1.populations FOR EACH ROW EXECUTE FUNCTION game_1.add_population_relations();


--
-- TOC entry 5201 (class 2620 OID 96375)
-- Name: productionShares trg_after_productionshares_insert; Type: TRIGGER; Schema: game_1; Owner: postgres
--

CREATE TRIGGER trg_after_productionshares_insert AFTER INSERT ON game_1."productionShares" FOR EACH ROW EXECUTE FUNCTION game_1.add_production_shares_to_populations();


--
-- TOC entry 5202 (class 2620 OID 96376)
-- Name: resources trg_after_resources_insert; Type: TRIGGER; Schema: game_1; Owner: postgres
--

CREATE TRIGGER trg_after_resources_insert AFTER INSERT ON game_1.resources FOR EACH ROW EXECUTE FUNCTION game_1.add_resource_to_all_nations();


--
-- TOC entry 5203 (class 2620 OID 96377)
-- Name: usedResources trg_after_usedresources_insert; Type: TRIGGER; Schema: game_1; Owner: postgres
--

CREATE TRIGGER trg_after_usedresources_insert AFTER INSERT ON game_1."usedResources" FOR EACH ROW EXECUTE FUNCTION game_1.add_used_resources_to_populations();


--
-- TOC entry 5199 (class 2620 OID 96378)
-- Name: nations trg_create_default_armies; Type: TRIGGER; Schema: game_1; Owner: postgres
--

CREATE TRIGGER trg_create_default_armies AFTER INSERT ON game_1.nations FOR EACH ROW EXECUTE FUNCTION game_1.create_default_armies();


--
-- TOC entry 5147 (class 2606 OID 96379)
-- Name: gameaccess FK_gameaccess_games_fk_Games; Type: FK CONSTRAINT; Schema: Global; Owner: postgres
--

ALTER TABLE ONLY "Global".gameaccess
    ADD CONSTRAINT "FK_gameaccess_games_fk_Games" FOREIGN KEY ("fk_Games") REFERENCES "Global".games(id) ON DELETE CASCADE;


--
-- TOC entry 5148 (class 2606 OID 96384)
-- Name: gameaccess FK_gameaccess_users_fk_Users; Type: FK CONSTRAINT; Schema: Global; Owner: postgres
--

ALTER TABLE ONLY "Global".gameaccess
    ADD CONSTRAINT "FK_gameaccess_users_fk_Users" FOREIGN KEY ("fk_Users") REFERENCES "Global".users(id) ON DELETE CASCADE;


--
-- TOC entry 5149 (class 2606 OID 96389)
-- Name: games FK_games_users_ownerId; Type: FK CONSTRAINT; Schema: Global; Owner: postgres
--

ALTER TABLE ONLY "Global".games
    ADD CONSTRAINT "FK_games_users_ownerId" FOREIGN KEY ("ownerId") REFERENCES "Global".users(id) ON DELETE CASCADE;


--
-- TOC entry 5150 (class 2606 OID 96394)
-- Name: refresh_tokens refresh_tokens_user_id_fkey; Type: FK CONSTRAINT; Schema: Global; Owner: postgres
--

ALTER TABLE ONLY "Global".refresh_tokens
    ADD CONSTRAINT refresh_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES "Global".users(id) ON DELETE CASCADE;


--
-- TOC entry 5151 (class 2606 OID 96399)
-- Name: accessToUnits FK_accessToUnits_fk_Nations; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1."accessToUnits"
    ADD CONSTRAINT "FK_accessToUnits_fk_Nations" FOREIGN KEY ("fk_Nation") REFERENCES game_1.nations(id) ON DELETE RESTRICT;


--
-- TOC entry 5152 (class 2606 OID 96404)
-- Name: accessToUnits FK_accessToUnits_fk_UnitTypes; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1."accessToUnits"
    ADD CONSTRAINT "FK_accessToUnits_fk_UnitTypes" FOREIGN KEY ("fk_UnitTypes") REFERENCES game_1."unitTypes"(id) ON DELETE CASCADE;


--
-- TOC entry 5153 (class 2606 OID 96409)
-- Name: accessestonations FK_accessestonations_fk_nations; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.accessestonations
    ADD CONSTRAINT "FK_accessestonations_fk_nations" FOREIGN KEY (fk_nations) REFERENCES game_1.nations(id) ON DELETE CASCADE;


--
-- TOC entry 5154 (class 2606 OID 96414)
-- Name: accessestonations FK_accessestonations_fk_users; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.accessestonations
    ADD CONSTRAINT "FK_accessestonations_fk_users" FOREIGN KEY (fk_users) REFERENCES game_1.players(id) ON DELETE CASCADE;


--
-- TOC entry 5155 (class 2606 OID 96419)
-- Name: actions FK_actions_fk_Nations; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.actions
    ADD CONSTRAINT "FK_actions_fk_Nations" FOREIGN KEY ("fk_Nations") REFERENCES game_1.nations(id) ON DELETE RESTRICT;


--
-- TOC entry 5156 (class 2606 OID 96424)
-- Name: armies FK_armies_localisations_fk_localisations; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.armies
    ADD CONSTRAINT "FK_armies_localisations_fk_localisations" FOREIGN KEY (fk_localisations) REFERENCES game_1.localisations(id) ON DELETE CASCADE;


--
-- TOC entry 5157 (class 2606 OID 96429)
-- Name: armies FK_armies_nations_fk_Nations; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.armies
    ADD CONSTRAINT "FK_armies_nations_fk_Nations" FOREIGN KEY ("fk_Nations") REFERENCES game_1.nations(id) ON DELETE CASCADE;


--
-- TOC entry 5158 (class 2606 OID 96434)
-- Name: factions FK_factions_fk_Nations; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.factions
    ADD CONSTRAINT "FK_factions_fk_Nations" FOREIGN KEY ("fk_Nations") REFERENCES game_1.nations(id) ON DELETE RESTRICT;


--
-- TOC entry 5160 (class 2606 OID 96439)
-- Name: localisationsResources FK_localisationsResources_localisations_fk_localisations; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1."localisationsResources"
    ADD CONSTRAINT "FK_localisationsResources_localisations_fk_localisations" FOREIGN KEY (fk_localisations) REFERENCES game_1.localisations(id) ON DELETE CASCADE;


--
-- TOC entry 5161 (class 2606 OID 96444)
-- Name: localisationsResources FK_localisationsResources_resources_fk_Resources; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1."localisationsResources"
    ADD CONSTRAINT "FK_localisationsResources_resources_fk_Resources" FOREIGN KEY ("fk_Resources") REFERENCES game_1.resources(id) ON DELETE CASCADE;


--
-- TOC entry 5159 (class 2606 OID 96449)
-- Name: localisations FK_localisations_nations_fk_nations; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.localisations
    ADD CONSTRAINT "FK_localisations_nations_fk_nations" FOREIGN KEY (fk_nations) REFERENCES game_1.nations(id) ON DELETE RESTRICT;


--
-- TOC entry 5162 (class 2606 OID 96454)
-- Name: maintenanceCosts FK_maintenanceCosts_fk_Resources; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1."maintenanceCosts"
    ADD CONSTRAINT "FK_maintenanceCosts_fk_Resources" FOREIGN KEY ("fk_Resources") REFERENCES game_1.resources(id) ON DELETE CASCADE;


--
-- TOC entry 5163 (class 2606 OID 96459)
-- Name: maintenanceCosts FK_maintenanceCosts_fk_UnitTypes; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1."maintenanceCosts"
    ADD CONSTRAINT "FK_maintenanceCosts_fk_UnitTypes" FOREIGN KEY ("fk_UnitTypes") REFERENCES game_1."unitTypes"(id) ON DELETE CASCADE;


--
-- TOC entry 5164 (class 2606 OID 96464)
-- Name: mapAccess FK_mapAccess_map_fk_Maps; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1."mapAccess"
    ADD CONSTRAINT "FK_mapAccess_map_fk_Maps" FOREIGN KEY ("fk_Maps") REFERENCES game_1.map(id) ON DELETE CASCADE;


--
-- TOC entry 5165 (class 2606 OID 96469)
-- Name: mapAccess FK_mapAccess_map_fk_Nation; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1."mapAccess"
    ADD CONSTRAINT "FK_mapAccess_map_fk_Nation" FOREIGN KEY ("fk_Nations") REFERENCES game_1.nations(id) ON DELETE CASCADE;


--
-- TOC entry 5167 (class 2606 OID 96474)
-- Name: nations FK_nations_players_fk_cultures; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.nations
    ADD CONSTRAINT "FK_nations_players_fk_cultures" FOREIGN KEY (fk_cultures) REFERENCES game_1.cultures(id) ON DELETE CASCADE;


--
-- TOC entry 5168 (class 2606 OID 96479)
-- Name: nations FK_nations_players_fk_religions; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.nations
    ADD CONSTRAINT "FK_nations_players_fk_religions" FOREIGN KEY (fk_religions) REFERENCES game_1.religions(id) ON DELETE RESTRICT;


--
-- TOC entry 5169 (class 2606 OID 96484)
-- Name: offeredresources FK_offeredresources_resources_fk_resource; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.offeredresources
    ADD CONSTRAINT "FK_offeredresources_resources_fk_resource" FOREIGN KEY (fk_resource) REFERENCES game_1.resources(id) ON DELETE CASCADE;


--
-- TOC entry 5170 (class 2606 OID 96489)
-- Name: offeredresources FK_offeredresources_tradeagreements_fk_tradeagreement; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.offeredresources
    ADD CONSTRAINT "FK_offeredresources_tradeagreements_fk_tradeagreement" FOREIGN KEY (fk_tradeagreement) REFERENCES game_1.tradeagreements(id) ON DELETE CASCADE;


--
-- TOC entry 5171 (class 2606 OID 96494)
-- Name: ownedResources FK_ownedresources_nation_fk_nation; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1."ownedResources"
    ADD CONSTRAINT "FK_ownedresources_nation_fk_nation" FOREIGN KEY (fk_nation) REFERENCES game_1.nations(id) ON DELETE RESTRICT;


--
-- TOC entry 5172 (class 2606 OID 96499)
-- Name: ownedResources FK_ownedresources_resource_fk_resource; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1."ownedResources"
    ADD CONSTRAINT "FK_ownedresources_resource_fk_resource" FOREIGN KEY (fk_resource) REFERENCES game_1.resources(id) ON DELETE CASCADE;


--
-- TOC entry 5173 (class 2606 OID 96504)
-- Name: players FK_players_users_fk_users; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.players
    ADD CONSTRAINT "FK_players_users_fk_users" FOREIGN KEY ("fk_User") REFERENCES "Global".users(id) ON DELETE CASCADE;


--
-- TOC entry 5176 (class 2606 OID 96509)
-- Name: populations FK_populations_cultures_fk_cultures; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.populations
    ADD CONSTRAINT "FK_populations_cultures_fk_cultures" FOREIGN KEY (fk_cultures) REFERENCES game_1.cultures(id) ON DELETE CASCADE;


--
-- TOC entry 5177 (class 2606 OID 96514)
-- Name: populations FK_populations_localisations_fk_localisations; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.populations
    ADD CONSTRAINT "FK_populations_localisations_fk_localisations" FOREIGN KEY (fk_localisations) REFERENCES game_1.localisations(id) ON DELETE CASCADE;


--
-- TOC entry 5178 (class 2606 OID 96519)
-- Name: populations FK_populations_religions_fk_religions; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.populations
    ADD CONSTRAINT "FK_populations_religions_fk_religions" FOREIGN KEY (fk_religions) REFERENCES game_1.religions(id) ON DELETE RESTRICT;


--
-- TOC entry 5179 (class 2606 OID 96524)
-- Name: populations FK_populations_socialgroups_fk_socialgroups; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.populations
    ADD CONSTRAINT "FK_populations_socialgroups_fk_socialgroups" FOREIGN KEY (fk_socialgroups) REFERENCES game_1.socialgroups(id) ON DELETE CASCADE;


--
-- TOC entry 5182 (class 2606 OID 96529)
-- Name: productionCost FK_productionCost_resources_fk_Resources; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1."productionCost"
    ADD CONSTRAINT "FK_productionCost_resources_fk_Resources" FOREIGN KEY ("fk_Resources") REFERENCES game_1.resources(id) ON DELETE CASCADE;


--
-- TOC entry 5183 (class 2606 OID 96534)
-- Name: productionCost FK_productionCost_unitTypes_fk_UnitTypes; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1."productionCost"
    ADD CONSTRAINT "FK_productionCost_unitTypes_fk_UnitTypes" FOREIGN KEY ("fk_UnitTypes") REFERENCES game_1."unitTypes"(id) ON DELETE CASCADE;


--
-- TOC entry 5184 (class 2606 OID 96539)
-- Name: productionShares FK_productionShares_populations_fk_Resources; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1."productionShares"
    ADD CONSTRAINT "FK_productionShares_populations_fk_Resources" FOREIGN KEY ("fk_Resources") REFERENCES game_1.resources(id) ON DELETE CASCADE;


--
-- TOC entry 5185 (class 2606 OID 96544)
-- Name: productionShares FK_productionShares_populations_fk_SocialGroups; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1."productionShares"
    ADD CONSTRAINT "FK_productionShares_populations_fk_SocialGroups" FOREIGN KEY ("fk_SocialGroups") REFERENCES game_1.socialgroups(id) ON DELETE CASCADE;


--
-- TOC entry 5186 (class 2606 OID 96549)
-- Name: relatedEvents FK_relatedEvents_events_fk_Events; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1."relatedEvents"
    ADD CONSTRAINT "FK_relatedEvents_events_fk_Events" FOREIGN KEY ("fk_Events") REFERENCES game_1.events(id) ON DELETE CASCADE;


--
-- TOC entry 5187 (class 2606 OID 96554)
-- Name: relatedEvents FK_relatedEvents_nations_fk_Nations; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1."relatedEvents"
    ADD CONSTRAINT "FK_relatedEvents_nations_fk_Nations" FOREIGN KEY ("fk_Nations") REFERENCES game_1.nations(id) ON DELETE RESTRICT;


--
-- TOC entry 5188 (class 2606 OID 96559)
-- Name: tradeagreements FK_tradeagreements_nations_fk_nationoffering; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.tradeagreements
    ADD CONSTRAINT "FK_tradeagreements_nations_fk_nationoffering" FOREIGN KEY (fk_nationoffering) REFERENCES game_1.nations(id) ON DELETE RESTRICT;


--
-- TOC entry 5189 (class 2606 OID 96564)
-- Name: tradeagreements FK_tradeagreements_nations_fk_nationreceiving; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.tradeagreements
    ADD CONSTRAINT "FK_tradeagreements_nations_fk_nationreceiving" FOREIGN KEY (fk_nationreceiving) REFERENCES game_1.nations(id) ON DELETE RESTRICT;


--
-- TOC entry 5190 (class 2606 OID 96569)
-- Name: troops FK_troops_armies_fk_Armies; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.troops
    ADD CONSTRAINT "FK_troops_armies_fk_Armies" FOREIGN KEY ("fk_Armies") REFERENCES game_1.armies(id) ON DELETE CASCADE;


--
-- TOC entry 5191 (class 2606 OID 96574)
-- Name: troops FK_troops_unitTypes_fk_UnitTypes; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.troops
    ADD CONSTRAINT "FK_troops_unitTypes_fk_UnitTypes" FOREIGN KEY ("fk_UnitTypes") REFERENCES game_1."unitTypes"(id) ON DELETE CASCADE;


--
-- TOC entry 5192 (class 2606 OID 96579)
-- Name: unitOrders FK_unitOrders_nations_fk_Nations; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1."unitOrders"
    ADD CONSTRAINT "FK_unitOrders_nations_fk_Nations" FOREIGN KEY ("fk_Nations") REFERENCES game_1.nations(id) ON DELETE RESTRICT;


--
-- TOC entry 5193 (class 2606 OID 96584)
-- Name: unitOrders FK_unitOrders_unitTypes_fk_UnitTypes; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1."unitOrders"
    ADD CONSTRAINT "FK_unitOrders_unitTypes_fk_UnitTypes" FOREIGN KEY ("fk_UnitTypes") REFERENCES game_1."unitTypes"(id) ON DELETE CASCADE;


--
-- TOC entry 5194 (class 2606 OID 96589)
-- Name: usedResources FK_usedResources_populations_fk_Resources; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1."usedResources"
    ADD CONSTRAINT "FK_usedResources_populations_fk_Resources" FOREIGN KEY ("fk_Resources") REFERENCES game_1.resources(id) ON DELETE CASCADE;


--
-- TOC entry 5195 (class 2606 OID 96594)
-- Name: usedResources FK_usedResources_populations_fk_SocialGroups; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1."usedResources"
    ADD CONSTRAINT "FK_usedResources_populations_fk_SocialGroups" FOREIGN KEY ("fk_SocialGroups") REFERENCES game_1.socialgroups(id) ON DELETE CASCADE;


--
-- TOC entry 5196 (class 2606 OID 96599)
-- Name: wantedresources FK_wantedresources_resources_fk_resource; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.wantedresources
    ADD CONSTRAINT "FK_wantedresources_resources_fk_resource" FOREIGN KEY (fk_resource) REFERENCES game_1.resources(id) ON DELETE CASCADE;


--
-- TOC entry 5197 (class 2606 OID 96604)
-- Name: wantedresources FK_wantedresources_tradeagreements_fk_tradeagreement; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.wantedresources
    ADD CONSTRAINT "FK_wantedresources_tradeagreements_fk_tradeagreement" FOREIGN KEY (fk_tradeagreement) REFERENCES game_1.tradeagreements(id) ON DELETE CASCADE;


--
-- TOC entry 5166 (class 2606 OID 96609)
-- Name: modifiers modifiers_event_id_fkey; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.modifiers
    ADD CONSTRAINT modifiers_event_id_fkey FOREIGN KEY (event_id) REFERENCES game_1.events(id) ON DELETE CASCADE;


--
-- TOC entry 5174 (class 2606 OID 96614)
-- Name: populationproductionshares populationproductionshares_fkpopulation_fkey; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.populationproductionshares
    ADD CONSTRAINT populationproductionshares_fkpopulation_fkey FOREIGN KEY (fk_population) REFERENCES game_1.populations(id) ON DELETE CASCADE;


--
-- TOC entry 5175 (class 2606 OID 96619)
-- Name: populationproductionshares populationproductionshares_fkresources_fkey; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.populationproductionshares
    ADD CONSTRAINT populationproductionshares_fkresources_fkey FOREIGN KEY (fk_resources) REFERENCES game_1.resources(id) ON DELETE CASCADE;


--
-- TOC entry 5180 (class 2606 OID 96624)
-- Name: populationusedresource populationusedresource_fkpopulation_fkey; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.populationusedresource
    ADD CONSTRAINT populationusedresource_fkpopulation_fkey FOREIGN KEY (fk_population) REFERENCES game_1.populations(id) ON DELETE CASCADE;


--
-- TOC entry 5181 (class 2606 OID 96629)
-- Name: populationusedresource populationusedresource_fkresources_fkey; Type: FK CONSTRAINT; Schema: game_1; Owner: postgres
--

ALTER TABLE ONLY game_1.populationusedresource
    ADD CONSTRAINT populationusedresource_fkresources_fkey FOREIGN KEY (fk_resources) REFERENCES game_1.resources(id) ON DELETE CASCADE;


-- Completed on 2026-02-15 18:30:02

--
-- PostgreSQL database dump complete
--

\unrestrict 5Dd2IgwOLlIU84q20HYGYJsYgngmQacQLWJUFrgwJxjb9ubg417RqHoHYcgmKqO

